import {
    InfinityIcon,
    AArrowDownIcon,
    AArrowUpIcon,
    ALargeSmallIcon,
    AccessibilityIcon,
    ActivityIcon,
    AirVentIcon,
    AirplayIcon,
    AlarmClockCheckIcon,
    AlarmClockIcon,
    AlarmClockMinusIcon,
    AlarmClockOffIcon,
    AlarmClockPlusIcon,
    AlarmSmokeIcon,
    AlbumIcon,
    AlignCenterHorizontalIcon,
    AlignCenterVerticalIcon,
    AlignEndHorizontalIcon,
    AlignEndVerticalIcon,
    AlignHorizontalDistributeCenterIcon,
    AlignHorizontalDistributeEndIcon,
    AlignHorizontalDistributeStartIcon,
    AlignHorizontalJustifyCenterIcon,
    AlignHorizontalJustifyEndIcon,
    AlignHorizontalJustifyStartIcon,
    AlignHorizontalSpaceAroundIcon,
    AlignHorizontalSpaceBetweenIcon,
    AlignStartHorizontalIcon,
    AlignStartVerticalIcon,
    AlignVerticalDistributeCenterIcon,
    AlignVerticalDistributeEndIcon,
    AlignVerticalDistributeStartIcon,
    AlignVerticalJustifyCenterIcon,
    AlignVerticalJustifyEndIcon,
    AlignVerticalJustifyStartIcon,
    AlignVerticalSpaceAroundIcon,
    AlignVerticalSpaceBetweenIcon,
    AmbulanceIcon,
    AmpersandIcon,
    AmpersandsIcon,
    AmphoraIcon,
    AnchorIcon,
    AngryIcon,
    AnnoyedIcon,
    AntennaIcon,
    AnvilIcon,
    ApertureIcon,
    AppWindowIcon,
    AppWindowMacIcon,
    AppleIcon,
    ArchiveIcon,
    ArchiveRestoreIcon,
    ArchiveXIcon,
    ArmchairIcon,
    ArrowBigDownDashIcon,
    ArrowBigDownIcon,
    ArrowBigLeftDashIcon,
    ArrowBigLeftIcon,
    ArrowBigRightDashIcon,
    ArrowBigRightIcon,
    ArrowBigUpDashIcon,
    ArrowBigUpIcon,
    ArrowDown01Icon,
    ArrowDown10Icon,
    ArrowDownAZIcon,
    ArrowDownFromLineIcon,
    ArrowDownIcon,
    ArrowDownLeftIcon,
    ArrowDownNarrowWideIcon,
    ArrowDownRightIcon,
    ArrowDownToDotIcon,
    ArrowDownToLineIcon,
    ArrowDownUpIcon,
    ArrowDownWideNarrowIcon,
    ArrowDownZAIcon,
    ArrowLeftFromLineIcon,
    ArrowLeftIcon,
    ArrowLeftRightIcon,
    ArrowLeftToLineIcon,
    ArrowRightFromLineIcon,
    ArrowRightIcon,
    ArrowRightLeftIcon,
    ArrowRightToLineIcon,
    ArrowUp01Icon,
    ArrowUp10Icon,
    ArrowUpAZIcon,
    ArrowUpDownIcon,
    ArrowUpFromDotIcon,
    ArrowUpFromLineIcon,
    ArrowUpIcon,
    ArrowUpLeftIcon,
    ArrowUpNarrowWideIcon,
    ArrowUpRightIcon,
    ArrowUpToLineIcon,
    ArrowUpWideNarrowIcon,
    ArrowUpZAIcon,
    ArrowsUpFromLineIcon,
    AsteriskIcon,
    AtSignIcon,
    AtomIcon,
    AudioLinesIcon,
    AudioWaveformIcon,
    AwardIcon,
    AxeIcon,
    Axis3dIcon,
    BabyIcon,
    BackpackIcon,
    BadgeAlertIcon,
    BadgeCentIcon,
    BadgeCheckIcon,
    BadgeDollarSignIcon,
    BadgeEuroIcon,
    BadgeIcon,
    BadgeIndianRupeeIcon,
    BadgeInfoIcon,
    BadgeJapaneseYenIcon,
    BadgeMinusIcon,
    BadgePercentIcon,
    BadgePlusIcon,
    BadgePoundSterlingIcon,
    BadgeQuestionMarkIcon,
    BadgeRussianRubleIcon,
    BadgeSwissFrancIcon,
    BadgeTurkishLiraIcon,
    BadgeXIcon,
    BaggageClaimIcon,
    BanIcon,
    BananaIcon,
    BandageIcon,
    BanknoteArrowDownIcon,
    BanknoteArrowUpIcon,
    BanknoteIcon,
    BanknoteXIcon,
    BarcodeIcon,
    BarrelIcon,
    BaselineIcon,
    BathIcon,
    BatteryChargingIcon,
    BatteryFullIcon,
    BatteryIcon,
    BatteryLowIcon,
    BatteryMediumIcon,
    BatteryPlusIcon,
    BatteryWarningIcon,
    BeakerIcon,
    BeanIcon,
    BeanOffIcon,
    BedDoubleIcon,
    BedIcon,
    BedSingleIcon,
    BeefIcon,
    BeerIcon,
    BeerOffIcon,
    BellDotIcon,
    BellElectricIcon,
    BellIcon,
    BellMinusIcon,
    BellOffIcon,
    BellPlusIcon,
    BellRingIcon,
    BetweenHorizontalEndIcon,
    BetweenHorizontalStartIcon,
    BetweenVerticalEndIcon,
    BetweenVerticalStartIcon,
    BicepsFlexedIcon,
    BikeIcon,
    BinaryIcon,
    BinocularsIcon,
    BiohazardIcon,
    BirdIcon,
    BirdhouseIcon,
    BitcoinIcon,
    BlendIcon,
    BlindsIcon,
    BlocksIcon,
    BluetoothConnectedIcon,
    BluetoothIcon,
    BluetoothOffIcon,
    BluetoothSearchingIcon,
    BoldIcon,
    BoltIcon,
    BombIcon,
    BoneIcon,
    BookAIcon,
    BookAlertIcon,
    BookAudioIcon,
    BookCheckIcon,
    BookCopyIcon,
    BookDashedIcon,
    BookDownIcon,
    BookHeadphonesIcon,
    BookHeartIcon,
    BookIcon,
    BookImageIcon,
    BookKeyIcon,
    BookLockIcon,
    BookMarkedIcon,
    BookMinusIcon,
    BookOpenCheckIcon,
    BookOpenIcon,
    BookOpenTextIcon,
    BookPlusIcon,
    BookTextIcon,
    BookTypeIcon,
    BookUp2Icon,
    BookUpIcon,
    BookUserIcon,
    BookXIcon,
    BookmarkCheckIcon,
    BookmarkIcon,
    BookmarkMinusIcon,
    BookmarkPlusIcon,
    BookmarkXIcon,
    BoomBoxIcon,
    BotIcon,
    BotMessageSquareIcon,
    BotOffIcon,
    BottleWineIcon,
    BowArrowIcon,
    BoxIcon,
    BoxesIcon,
    BracesIcon,
    BracketsIcon,
    BrainCircuitIcon,
    BrainCogIcon,
    BrainIcon,
    BrickWallFireIcon,
    BrickWallIcon,
    BrickWallShieldIcon,
    BriefcaseBusinessIcon,
    BriefcaseConveyorBeltIcon,
    BriefcaseIcon,
    BriefcaseMedicalIcon,
    BringToFrontIcon,
    BrushCleaningIcon,
    BrushIcon,
    BubblesIcon,
    BugIcon,
    BugOffIcon,
    BugPlayIcon,
    Building2Icon,
    BuildingIcon,
    BusFrontIcon,
    BusIcon,
    CableCarIcon,
    CableIcon,
    CakeIcon,
    CakeSliceIcon,
    CalculatorIcon,
    Calendar1Icon,
    CalendarArrowDownIcon,
    CalendarArrowUpIcon,
    CalendarCheck2Icon,
    CalendarCheckIcon,
    CalendarClockIcon,
    CalendarCogIcon,
    CalendarDaysIcon,
    CalendarFoldIcon,
    CalendarHeartIcon,
    CalendarIcon,
    CalendarMinus2Icon,
    CalendarMinusIcon,
    CalendarOffIcon,
    CalendarPlus2Icon,
    CalendarPlusIcon,
    CalendarRangeIcon,
    CalendarSearchIcon,
    CalendarSyncIcon,
    CalendarX2Icon,
    CalendarXIcon,
    CameraIcon,
    CameraOffIcon,
    CandyCaneIcon,
    CandyIcon,
    CandyOffIcon,
    CannabisIcon,
    CaptionsIcon,
    CaptionsOffIcon,
    CarFrontIcon,
    CarIcon,
    CarTaxiFrontIcon,
    CaravanIcon,
    CardSimIcon,
    CarrotIcon,
    CaseLowerIcon,
    CaseSensitiveIcon,
    CaseUpperIcon,
    CassetteTapeIcon,
    CastIcon,
    CastleIcon,
    CatIcon,
    CctvIcon,
    ChartAreaIcon,
    ChartBarBigIcon,
    ChartBarDecreasingIcon,
    ChartBarIcon,
    ChartBarIncreasingIcon,
    ChartBarStackedIcon,
    ChartCandlestickIcon,
    ChartColumnBigIcon,
    ChartColumnDecreasingIcon,
    ChartColumnIcon,
    ChartColumnIncreasingIcon,
    ChartColumnStackedIcon,
    ChartGanttIcon,
    ChartLineIcon,
    ChartNetworkIcon,
    ChartNoAxesColumnDecreasingIcon,
    ChartNoAxesColumnIcon,
    ChartNoAxesColumnIncreasingIcon,
    ChartNoAxesCombinedIcon,
    ChartNoAxesGanttIcon,
    ChartPieIcon,
    ChartScatterIcon,
    ChartSplineIcon,
    CheckCheckIcon,
    CheckIcon,
    CheckLineIcon,
    ChefHatIcon,
    CherryIcon,
    ChessBishopIcon,
    ChessKingIcon,
    ChessKnightIcon,
    ChessPawnIcon,
    ChessQueenIcon,
    ChessRookIcon,
    ChevronDownIcon,
    ChevronFirstIcon,
    ChevronLastIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChevronsDownIcon,
    ChevronsDownUpIcon,
    ChevronsLeftIcon,
    ChevronsLeftRightEllipsisIcon,
    ChevronsLeftRightIcon,
    ChevronsRightIcon,
    ChevronsRightLeftIcon,
    ChevronsUpDownIcon,
    ChevronsUpIcon,
    ChromiumIcon,
    ChurchIcon,
    CigaretteIcon,
    CigaretteOffIcon,
    CircleAlertIcon,
    CircleArrowDownIcon,
    CircleArrowLeftIcon,
    CircleArrowOutDownLeftIcon,
    CircleArrowOutDownRightIcon,
    CircleArrowOutUpLeftIcon,
    CircleArrowOutUpRightIcon,
    CircleArrowRightIcon,
    CircleArrowUpIcon,
    CircleCheckBigIcon,
    CircleCheckIcon,
    CircleChevronDownIcon,
    CircleChevronLeftIcon,
    CircleChevronRightIcon,
    CircleChevronUpIcon,
    CircleDashedIcon,
    CircleDivideIcon,
    CircleDollarSignIcon,
    CircleDotDashedIcon,
    CircleDotIcon,
    CircleEllipsisIcon,
    CircleEqualIcon,
    CircleFadingArrowUpIcon,
    CircleFadingPlusIcon,
    CircleGaugeIcon,
    CircleIcon,
    CircleMinusIcon,
    CircleOffIcon,
    CircleParkingIcon,
    CircleParkingOffIcon,
    CirclePauseIcon,
    CirclePercentIcon,
    CirclePlayIcon,
    CirclePlusIcon,
    CirclePoundSterlingIcon,
    CirclePowerIcon,
    CircleQuestionMarkIcon,
    CircleSlash2Icon,
    CircleSlashIcon,
    CircleSmallIcon,
    CircleStarIcon,
    CircleStopIcon,
    CircleUserIcon,
    CircleUserRoundIcon,
    CircleXIcon,
    CircuitBoardIcon,
    CitrusIcon,
    ClapperboardIcon,
    ClipboardCheckIcon,
    ClipboardClockIcon,
    ClipboardCopyIcon,
    ClipboardIcon,
    ClipboardListIcon,
    ClipboardMinusIcon,
    ClipboardPasteIcon,
    ClipboardPenIcon,
    ClipboardPenLineIcon,
    ClipboardPlusIcon,
    ClipboardTypeIcon,
    ClipboardXIcon,
    Clock1Icon,
    Clock2Icon,
    Clock3Icon,
    Clock4Icon,
    Clock5Icon,
    Clock6Icon,
    Clock7Icon,
    Clock8Icon,
    Clock9Icon,
    Clock10Icon,
    Clock11Icon,
    Clock12Icon,
    ClockAlertIcon,
    ClockArrowDownIcon,
    ClockArrowUpIcon,
    ClockCheckIcon,
    ClockFadingIcon,
    ClockIcon,
    ClockPlusIcon,
    ClosedCaptionIcon,
    CloudAlertIcon,
    CloudCheckIcon,
    CloudCogIcon,
    CloudDownloadIcon,
    CloudDrizzleIcon,
    CloudFogIcon,
    CloudHailIcon,
    CloudIcon,
    CloudLightningIcon,
    CloudMoonIcon,
    CloudMoonRainIcon,
    CloudOffIcon,
    CloudRainIcon,
    CloudRainWindIcon,
    CloudSnowIcon,
    CloudSunIcon,
    CloudSunRainIcon,
    CloudUploadIcon,
    CloudyIcon,
    CloverIcon,
    ClubIcon,
    CodeIcon,
    CodeXmlIcon,
    CodepenIcon,
    CodesandboxIcon,
    CoffeeIcon,
    CogIcon,
    CoinsIcon,
    Columns2Icon,
    Columns3CogIcon,
    Columns3Icon,
    Columns4Icon,
    CombineIcon,
    CommandIcon,
    CompassIcon,
    ComponentIcon,
    ComputerIcon,
    ConciergeBellIcon,
    ConeIcon,
    ConstructionIcon,
    ContactIcon,
    ContactRoundIcon,
    ContainerIcon,
    ContrastIcon,
    CookieIcon,
    CookingPotIcon,
    CopyCheckIcon,
    CopyIcon,
    CopyMinusIcon,
    CopyPlusIcon,
    CopySlashIcon,
    CopyXIcon,
    CopyleftIcon,
    CopyrightIcon,
    CornerDownLeftIcon,
    CornerDownRightIcon,
    CornerLeftDownIcon,
    CornerLeftUpIcon,
    CornerRightDownIcon,
    CornerRightUpIcon,
    CornerUpLeftIcon,
    CornerUpRightIcon,
    CpuIcon,
    CreativeCommonsIcon,
    CreditCardIcon,
    CroissantIcon,
    CropIcon,
    CrossIcon,
    CrosshairIcon,
    CrownIcon,
    CuboidIcon,
    CupSodaIcon,
    CurrencyIcon,
    CylinderIcon,
    DamIcon,
    DatabaseBackupIcon,
    DatabaseIcon,
    DatabaseZapIcon,
    DecimalsArrowLeftIcon,
    DecimalsArrowRightIcon,
    DeleteIcon,
    DessertIcon,
    DiameterIcon,
    DiamondIcon,
    DiamondMinusIcon,
    DiamondPercentIcon,
    DiamondPlusIcon,
    Dice1Icon,
    Dice2Icon,
    Dice3Icon,
    Dice4Icon,
    Dice5Icon,
    Dice6Icon,
    DicesIcon,
    DiffIcon,
    Disc2Icon,
    Disc3Icon,
    DiscAlbumIcon,
    DiscIcon,
    DivideIcon,
    DnaIcon,
    DnaOffIcon,
    DockIcon,
    DogIcon,
    DollarSignIcon,
    DonutIcon,
    DoorClosedIcon,
    DoorClosedLockedIcon,
    DoorOpenIcon,
    DotIcon,
    DownloadIcon,
    DraftingCompassIcon,
    DramaIcon,
    DribbbleIcon,
    DrillIcon,
    DroneIcon,
    DropletIcon,
    DropletOffIcon,
    DropletsIcon,
    DrumIcon,
    DrumstickIcon,
    DumbbellIcon,
    EarIcon,
    EarOffIcon,
    EarthIcon,
    EarthLockIcon,
    EclipseIcon,
    EggFriedIcon,
    EggIcon,
    EggOffIcon,
    EllipsisIcon,
    EllipsisVerticalIcon,
    EqualApproximatelyIcon,
    EqualIcon,
    EqualNotIcon,
    EraserIcon,
    EthernetPortIcon,
    EuroIcon,
    EvChargerIcon,
    ExpandIcon,
    ExternalLinkIcon,
    EyeClosedIcon,
    EyeIcon,
    EyeOffIcon,
    FacebookIcon,
    FactoryIcon,
    FanIcon,
    FastForwardIcon,
    FeatherIcon,
    FenceIcon,
    FerrisWheelIcon,
    FigmaIcon,
    FileArchiveIcon,
    FileAxis3dIcon,
    FileBadgeIcon,
    FileBoxIcon,
    FileBracesCornerIcon,
    FileBracesIcon,
    FileChartColumnIcon,
    FileChartColumnIncreasingIcon,
    FileChartLineIcon,
    FileChartPieIcon,
    FileCheckCornerIcon,
    FileCheckIcon,
    FileClockIcon,
    FileCodeCornerIcon,
    FileCodeIcon,
    FileCogIcon,
    FileDiffIcon,
    FileDigitIcon,
    FileDownIcon,
    FileExclamationPointIcon,
    FileHeadphoneIcon,
    FileHeartIcon,
    FileIcon,
    FileImageIcon,
    FileInputIcon,
    FileKeyIcon,
    FileLockIcon,
    FileMinusCornerIcon,
    FileMinusIcon,
    FileMusicIcon,
    FileOutputIcon,
    FilePenIcon,
    FilePenLineIcon,
    FilePlayIcon,
    FilePlusCornerIcon,
    FilePlusIcon,
    FileQuestionMarkIcon,
    FileScanIcon,
    FileSearchCornerIcon,
    FileSearchIcon,
    FileSignalIcon,
    FileSlidersIcon,
    FileSpreadsheetIcon,
    FileStackIcon,
    FileSymlinkIcon,
    FileTerminalIcon,
    FileTextIcon,
    FileTypeCornerIcon,
    FileTypeIcon,
    FileUpIcon,
    FileUserIcon,
    FileVideoCameraIcon,
    FileVolumeIcon,
    FileXCornerIcon,
    FileXIcon,
    FilesIcon,
    FilmIcon,
    FingerprintIcon,
    FireExtinguisherIcon,
    FishIcon,
    FishOffIcon,
    FishSymbolIcon,
    FlagIcon,
    FlagOffIcon,
    FlagTriangleLeftIcon,
    FlagTriangleRightIcon,
    FlameIcon,
    FlameKindlingIcon,
    FlashlightIcon,
    FlashlightOffIcon,
    FlaskConicalIcon,
    FlaskConicalOffIcon,
    FlaskRoundIcon,
    FlipHorizontal2Icon,
    FlipHorizontalIcon,
    FlipVertical2Icon,
    FlipVerticalIcon,
    Flower2Icon,
    FlowerIcon,
    FocusIcon,
    FoldHorizontalIcon,
    FoldVerticalIcon,
    FolderArchiveIcon,
    FolderCheckIcon,
    FolderClockIcon,
    FolderClosedIcon,
    FolderCodeIcon,
    FolderCogIcon,
    FolderDotIcon,
    FolderDownIcon,
    FolderGit2Icon,
    FolderGitIcon,
    FolderHeartIcon,
    FolderIcon,
    FolderInputIcon,
    FolderKanbanIcon,
    FolderKeyIcon,
    FolderLockIcon,
    FolderMinusIcon,
    FolderOpenDotIcon,
    FolderOpenIcon,
    FolderOutputIcon,
    FolderPenIcon,
    FolderPlusIcon,
    FolderRootIcon,
    FolderSearch2Icon,
    FolderSearchIcon,
    FolderSymlinkIcon,
    FolderSyncIcon,
    FolderTreeIcon,
    FolderUpIcon,
    FolderXIcon,
    FoldersIcon,
    FootprintsIcon,
    ForkliftIcon,
    ForwardIcon,
    FrameIcon,
    FramerIcon,
    FrownIcon,
    FuelIcon,
    FullscreenIcon,
    FunnelIcon,
    FunnelPlusIcon,
    FunnelXIcon,
    GalleryHorizontalEndIcon,
    GalleryHorizontalIcon,
    GalleryThumbnailsIcon,
    GalleryVerticalEndIcon,
    GalleryVerticalIcon,
    Gamepad2Icon,
    GamepadDirectionalIcon,
    GamepadIcon,
    GaugeIcon,
    GavelIcon,
    GemIcon,
    GeorgianLariIcon,
    GhostIcon,
    GiftIcon,
    GitBranchIcon,
    GitBranchMinusIcon,
    GitBranchPlusIcon,
    GitCommitHorizontalIcon,
    GitCommitVerticalIcon,
    GitCompareArrowsIcon,
    GitCompareIcon,
    GitForkIcon,
    GitGraphIcon,
    GitMergeIcon,
    GitPullRequestArrowIcon,
    GitPullRequestClosedIcon,
    GitPullRequestCreateArrowIcon,
    GitPullRequestCreateIcon,
    GitPullRequestDraftIcon,
    GitPullRequestIcon,
    GithubIcon,
    GitlabIcon,
    GlassWaterIcon,
    GlassesIcon,
    GlobeIcon,
    GlobeLockIcon,
    GoalIcon,
    GpuIcon,
    GraduationCapIcon,
    GrapeIcon,
    Grid2x2CheckIcon,
    Grid2x2Icon,
    Grid2x2PlusIcon,
    Grid2x2XIcon,
    Grid3x2Icon,
    Grid3x3Icon,
    GripHorizontalIcon,
    GripIcon,
    GripVerticalIcon,
    GroupIcon,
    GuitarIcon,
    HamIcon,
    HamburgerIcon,
    HammerIcon,
    HandCoinsIcon,
    HandFistIcon,
    HandGrabIcon,
    HandHeartIcon,
    HandHelpingIcon,
    HandIcon,
    HandMetalIcon,
    HandPlatterIcon,
    HandbagIcon,
    HandshakeIcon,
    HardDriveDownloadIcon,
    HardDriveIcon,
    HardDriveUploadIcon,
    HardHatIcon,
    HashIcon,
    HatGlassesIcon,
    HazeIcon,
    HdmiPortIcon,
    Heading1Icon,
    Heading2Icon,
    Heading3Icon,
    Heading4Icon,
    Heading5Icon,
    Heading6Icon,
    HeadingIcon,
    HeadphoneOffIcon,
    HeadphonesIcon,
    HeadsetIcon,
    HeartCrackIcon,
    HeartHandshakeIcon,
    HeartIcon,
    HeartMinusIcon,
    HeartOffIcon,
    HeartPlusIcon,
    HeartPulseIcon,
    HeaterIcon,
    HelicopterIcon,
    HexagonIcon,
    HighlighterIcon,
    HistoryIcon,
    HopIcon,
    HopOffIcon,
    HospitalIcon,
    HotelIcon,
    HourglassIcon,
    HouseHeartIcon,
    HouseIcon,
    HousePlugIcon,
    HousePlusIcon,
    HouseWifiIcon,
    IceCreamBowlIcon,
    IceCreamConeIcon,
    IdCardIcon,
    IdCardLanyardIcon,
    ImageDownIcon,
    ImageIcon,
    ImageMinusIcon,
    ImageOffIcon,
    ImagePlayIcon,
    ImagePlusIcon,
    ImageUpIcon,
    ImageUpscaleIcon,
    ImagesIcon,
    ImportIcon,
    InboxIcon,
    IndianRupeeIcon,
    InfoIcon,
    InspectionPanelIcon,
    InstagramIcon,
    ItalicIcon,
    IterationCcwIcon,
    IterationCwIcon,
    JapaneseYenIcon,
    JoystickIcon,
    KanbanIcon,
    KayakIcon,
    KeyIcon,
    KeyRoundIcon,
    KeySquareIcon,
    KeyboardIcon,
    KeyboardMusicIcon,
    KeyboardOffIcon,
    LampCeilingIcon,
    LampDeskIcon,
    LampFloorIcon,
    LampIcon,
    LampWallDownIcon,
    LampWallUpIcon,
    LandPlotIcon,
    LandmarkIcon,
    LanguagesIcon,
    LaptopIcon,
    LaptopMinimalCheckIcon,
    LaptopMinimalIcon,
    LassoIcon,
    LassoSelectIcon,
    LaughIcon,
    Layers2Icon,
    LayersIcon,
    LayoutDashboardIcon,
    LayoutGridIcon,
    LayoutListIcon,
    LayoutPanelLeftIcon,
    LayoutPanelTopIcon,
    LayoutTemplateIcon,
    LeafIcon,
    LeafyGreenIcon,
    LecternIcon,
    LibraryBigIcon,
    LibraryIcon,
    LifeBuoyIcon,
    LigatureIcon,
    LightbulbIcon,
    LightbulbOffIcon,
    LineSquiggleIcon,
    Link2Icon,
    Link2OffIcon,
    LinkIcon,
    LinkedinIcon,
    ListCheckIcon,
    ListChecksIcon,
    ListChevronsDownUpIcon,
    ListChevronsUpDownIcon,
    ListCollapseIcon,
    ListEndIcon,
    ListFilterIcon,
    ListFilterPlusIcon,
    ListIcon,
    ListIndentDecreaseIcon,
    ListIndentIncreaseIcon,
    ListMinusIcon,
    ListMusicIcon,
    ListOrderedIcon,
    ListPlusIcon,
    ListRestartIcon,
    ListStartIcon,
    ListTodoIcon,
    ListTreeIcon,
    ListVideoIcon,
    ListXIcon,
    LoaderCircleIcon,
    LoaderIcon,
    LoaderPinwheelIcon,
    LocateFixedIcon,
    LocateIcon,
    LocateOffIcon,
    LockIcon,
    LockKeyholeIcon,
    LockKeyholeOpenIcon,
    LockOpenIcon,
    LogInIcon,
    LogOutIcon,
    LogsIcon,
    LollipopIcon,
    LuggageIcon,
    MagnetIcon,
    MailCheckIcon,
    MailIcon,
    MailMinusIcon,
    MailOpenIcon,
    MailPlusIcon,
    MailQuestionMarkIcon,
    MailSearchIcon,
    MailWarningIcon,
    MailXIcon,
    MailboxIcon,
    MailsIcon,
    MapIcon,
    MapMinusIcon,
    MapPinCheckIcon,
    MapPinCheckInsideIcon,
    MapPinHouseIcon,
    MapPinIcon,
    MapPinMinusIcon,
    MapPinMinusInsideIcon,
    MapPinOffIcon,
    MapPinPenIcon,
    MapPinPlusIcon,
    MapPinPlusInsideIcon,
    MapPinXIcon,
    MapPinXInsideIcon,
    MapPinnedIcon,
    MapPlusIcon,
    MarsIcon,
    MarsStrokeIcon,
    MartiniIcon,
    Maximize2Icon,
    MaximizeIcon,
    MedalIcon,
    MegaphoneIcon,
    MegaphoneOffIcon,
    MehIcon,
    MemoryStickIcon,
    MenuIcon,
    MergeIcon,
    MessageCircleCodeIcon,
    MessageCircleDashedIcon,
    MessageCircleHeartIcon,
    MessageCircleIcon,
    MessageCircleMoreIcon,
    MessageCircleOffIcon,
    MessageCirclePlusIcon,
    MessageCircleQuestionMarkIcon,
    MessageCircleReplyIcon,
    MessageCircleWarningIcon,
    MessageCircleXIcon,
    MessageSquareCodeIcon,
    MessageSquareDashedIcon,
    MessageSquareDiffIcon,
    MessageSquareDotIcon,
    MessageSquareHeartIcon,
    MessageSquareIcon,
    MessageSquareLockIcon,
    MessageSquareMoreIcon,
    MessageSquareOffIcon,
    MessageSquarePlusIcon,
    MessageSquareQuoteIcon,
    MessageSquareReplyIcon,
    MessageSquareShareIcon,
    MessageSquareTextIcon,
    MessageSquareWarningIcon,
    MessageSquareXIcon,
    MessagesSquareIcon,
    MicIcon,
    MicOffIcon,
    MicVocalIcon,
    MicrochipIcon,
    MicroscopeIcon,
    MicrowaveIcon,
    MilestoneIcon,
    MilkIcon,
    MilkOffIcon,
    Minimize2Icon,
    MinimizeIcon,
    MinusIcon,
    MonitorCheckIcon,
    MonitorCloudIcon,
    MonitorCogIcon,
    MonitorDotIcon,
    MonitorDownIcon,
    MonitorIcon,
    MonitorOffIcon,
    MonitorPauseIcon,
    MonitorPlayIcon,
    MonitorSmartphoneIcon,
    MonitorSpeakerIcon,
    MonitorStopIcon,
    MonitorUpIcon,
    MonitorXIcon,
    MoonIcon,
    MoonStarIcon,
    MotorbikeIcon,
    MountainIcon,
    MountainSnowIcon,
    MouseIcon,
    MouseOffIcon,
    MousePointer2Icon,
    MousePointer2OffIcon,
    MousePointerBanIcon,
    MousePointerClickIcon,
    MousePointerIcon,
    Move3dIcon,
    MoveDiagonal2Icon,
    MoveDiagonalIcon,
    MoveDownIcon,
    MoveDownLeftIcon,
    MoveDownRightIcon,
    MoveHorizontalIcon,
    MoveIcon,
    MoveLeftIcon,
    MoveRightIcon,
    MoveUpIcon,
    MoveUpLeftIcon,
    MoveUpRightIcon,
    MoveVerticalIcon,
    Music2Icon,
    Music3Icon,
    Music4Icon,
    MusicIcon,
    Navigation2Icon,
    Navigation2OffIcon,
    NavigationIcon,
    NavigationOffIcon,
    NetworkIcon,
    NewspaperIcon,
    NfcIcon,
    NonBinaryIcon,
    NotebookIcon,
    NotebookPenIcon,
    NotebookTabsIcon,
    NotebookTextIcon,
    NotepadTextDashedIcon,
    NotepadTextIcon,
    NutIcon,
    NutOffIcon,
    OctagonAlertIcon,
    OctagonIcon,
    OctagonMinusIcon,
    OctagonPauseIcon,
    OctagonXIcon,
    OmegaIcon,
    OptionIcon,
    OrbitIcon,
    OrigamiIcon,
    Package2Icon,
    PackageCheckIcon,
    PackageIcon,
    PackageMinusIcon,
    PackageOpenIcon,
    PackagePlusIcon,
    PackageSearchIcon,
    PackageXIcon,
    PaintBucketIcon,
    PaintRollerIcon,
    PaintbrushIcon,
    PaintbrushVerticalIcon,
    PaletteIcon,
    PandaIcon,
    PanelBottomCloseIcon,
    PanelBottomDashedIcon,
    PanelBottomIcon,
    PanelBottomOpenIcon,
    PanelLeftCloseIcon,
    PanelLeftDashedIcon,
    PanelLeftIcon,
    PanelLeftOpenIcon,
    PanelLeftRightDashedIcon,
    PanelRightCloseIcon,
    PanelRightDashedIcon,
    PanelRightIcon,
    PanelRightOpenIcon,
    PanelTopBottomDashedIcon,
    PanelTopCloseIcon,
    PanelTopDashedIcon,
    PanelTopIcon,
    PanelTopOpenIcon,
    PanelsLeftBottomIcon,
    PanelsRightBottomIcon,
    PanelsTopLeftIcon,
    PaperclipIcon,
    ParenthesesIcon,
    ParkingMeterIcon,
    PartyPopperIcon,
    PauseIcon,
    PawPrintIcon,
    PcCaseIcon,
    PenIcon,
    PenLineIcon,
    PenOffIcon,
    PenToolIcon,
    PencilIcon,
    PencilLineIcon,
    PencilOffIcon,
    PencilRulerIcon,
    PentagonIcon,
    PercentIcon,
    PersonStandingIcon,
    PhilippinePesoIcon,
    PhoneCallIcon,
    PhoneForwardedIcon,
    PhoneIcon,
    PhoneIncomingIcon,
    PhoneMissedIcon,
    PhoneOffIcon,
    PhoneOutgoingIcon,
    PiIcon,
    PianoIcon,
    PickaxeIcon,
    PictureInPicture2Icon,
    PictureInPictureIcon,
    PiggyBankIcon,
    PilcrowIcon,
    PilcrowLeftIcon,
    PilcrowRightIcon,
    PillBottleIcon,
    PillIcon,
    PinIcon,
    PinOffIcon,
    PipetteIcon,
    PizzaIcon,
    PlaneIcon,
    PlaneLandingIcon,
    PlaneTakeoffIcon,
    PlayIcon,
    Plug2Icon,
    PlugIcon,
    PlugZapIcon,
    PlusIcon,
    PocketIcon,
    PocketKnifeIcon,
    PodcastIcon,
    PointerIcon,
    PointerOffIcon,
    PopcornIcon,
    PopsicleIcon,
    PoundSterlingIcon,
    PowerIcon,
    PowerOffIcon,
    PresentationIcon,
    PrinterCheckIcon,
    PrinterIcon,
    ProjectorIcon,
    ProportionsIcon,
    PuzzleIcon,
    PyramidIcon,
    QrCodeIcon,
    QuoteIcon,
    RabbitIcon,
    RadarIcon,
    RadiationIcon,
    RadicalIcon,
    RadioIcon,
    RadioReceiverIcon,
    RadioTowerIcon,
    RadiusIcon,
    RailSymbolIcon,
    RainbowIcon,
    RatIcon,
    RatioIcon,
    ReceiptCentIcon,
    ReceiptEuroIcon,
    ReceiptIcon,
    ReceiptIndianRupeeIcon,
    ReceiptJapaneseYenIcon,
    ReceiptPoundSterlingIcon,
    ReceiptRussianRubleIcon,
    ReceiptSwissFrancIcon,
    ReceiptTextIcon,
    ReceiptTurkishLiraIcon,
    RectangleCircleIcon,
    RectangleEllipsisIcon,
    RectangleGogglesIcon,
    RectangleHorizontalIcon,
    RectangleVerticalIcon,
    RecycleIcon,
    Redo2Icon,
    RedoDotIcon,
    RedoIcon,
    RefreshCcwDotIcon,
    RefreshCcwIcon,
    RefreshCwIcon,
    RefreshCwOffIcon,
    RefrigeratorIcon,
    RegexIcon,
    RemoveFormattingIcon,
    Repeat1Icon,
    Repeat2Icon,
    RepeatIcon,
    ReplaceAllIcon,
    ReplaceIcon,
    ReplyAllIcon,
    ReplyIcon,
    RewindIcon,
    RibbonIcon,
    RocketIcon,
    RockingChairIcon,
    RollerCoasterIcon,
    RoseIcon,
    Rotate3dIcon,
    RotateCcwIcon,
    RotateCcwKeyIcon,
    RotateCcwSquareIcon,
    RotateCwIcon,
    RotateCwSquareIcon,
    RouteIcon,
    RouteOffIcon,
    RouterIcon,
    Rows2Icon,
    Rows3Icon,
    Rows4Icon,
    RssIcon,
    RulerDimensionLineIcon,
    RulerIcon,
    RussianRubleIcon,
    SailboatIcon,
    SaladIcon,
    SandwichIcon,
    SatelliteDishIcon,
    SatelliteIcon,
    SaudiRiyalIcon,
    SaveAllIcon,
    SaveIcon,
    SaveOffIcon,
    Scale3dIcon,
    ScaleIcon,
    ScalingIcon,
    ScanBarcodeIcon,
    ScanEyeIcon,
    ScanFaceIcon,
    ScanHeartIcon,
    ScanIcon,
    ScanLineIcon,
    ScanQrCodeIcon,
    ScanSearchIcon,
    ScanTextIcon,
    SchoolIcon,
    ScissorsIcon,
    ScissorsLineDashedIcon,
    ScreenShareIcon,
    ScreenShareOffIcon,
    ScrollIcon,
    ScrollTextIcon,
    SearchCheckIcon,
    SearchCodeIcon,
    SearchIcon,
    SearchSlashIcon,
    SearchXIcon,
    SectionIcon,
    SendHorizontalIcon,
    SendIcon,
    SendToBackIcon,
    SeparatorHorizontalIcon,
    SeparatorVerticalIcon,
    ServerCogIcon,
    ServerCrashIcon,
    ServerIcon,
    ServerOffIcon,
    Settings2Icon,
    SettingsIcon,
    ShapesIcon,
    Share2Icon,
    ShareIcon,
    SheetIcon,
    ShellIcon,
    ShieldAlertIcon,
    ShieldBanIcon,
    ShieldCheckIcon,
    ShieldEllipsisIcon,
    ShieldHalfIcon,
    ShieldIcon,
    ShieldMinusIcon,
    ShieldOffIcon,
    ShieldPlusIcon,
    ShieldQuestionMarkIcon,
    ShieldUserIcon,
    ShieldXIcon,
    ShipIcon,
    ShipWheelIcon,
    ShirtIcon,
    ShoppingBagIcon,
    ShoppingBasketIcon,
    ShoppingCartIcon,
    ShovelIcon,
    ShowerHeadIcon,
    ShredderIcon,
    ShrimpIcon,
    ShrinkIcon,
    ShrubIcon,
    ShuffleIcon,
    SigmaIcon,
    SignalHighIcon,
    SignalIcon,
    SignalLowIcon,
    SignalMediumIcon,
    SignalZeroIcon,
    SignatureIcon,
    SignpostBigIcon,
    SignpostIcon,
    SirenIcon,
    SkipBackIcon,
    SkipForwardIcon,
    SkullIcon,
    SlackIcon,
    SlashIcon,
    SliceIcon,
    SlidersHorizontalIcon,
    SlidersVerticalIcon,
    SmartphoneChargingIcon,
    SmartphoneIcon,
    SmartphoneNfcIcon,
    SmileIcon,
    SmilePlusIcon,
    SnailIcon,
    SnowflakeIcon,
    SoapDispenserDropletIcon,
    SofaIcon,
    SolarPanelIcon,
    SoupIcon,
    SpaceIcon,
    SpadeIcon,
    SparkleIcon,
    SparklesIcon,
    SpeakerIcon,
    SpeechIcon,
    SpellCheck2Icon,
    SpellCheckIcon,
    SplineIcon,
    SplinePointerIcon,
    SplitIcon,
    SpoolIcon,
    SpotlightIcon,
    SprayCanIcon,
    SproutIcon,
    SquareActivityIcon,
    SquareArrowDownIcon,
    SquareArrowDownLeftIcon,
    SquareArrowDownRightIcon,
    SquareArrowLeftIcon,
    SquareArrowOutDownLeftIcon,
    SquareArrowOutDownRightIcon,
    SquareArrowOutUpLeftIcon,
    SquareArrowOutUpRightIcon,
    SquareArrowRightIcon,
    SquareArrowUpIcon,
    SquareArrowUpLeftIcon,
    SquareArrowUpRightIcon,
    SquareAsteriskIcon,
    SquareBottomDashedScissorsIcon,
    SquareChartGanttIcon,
    SquareCheckBigIcon,
    SquareCheckIcon,
    SquareChevronDownIcon,
    SquareChevronLeftIcon,
    SquareChevronRightIcon,
    SquareChevronUpIcon,
    SquareCodeIcon,
    SquareDashedBottomCodeIcon,
    SquareDashedBottomIcon,
    SquareDashedIcon,
    SquareDashedKanbanIcon,
    SquareDashedMousePointerIcon,
    SquareDashedTopSolidIcon,
    SquareDivideIcon,
    SquareDotIcon,
    SquareEqualIcon,
    SquareFunctionIcon,
    SquareIcon,
    SquareKanbanIcon,
    SquareLibraryIcon,
    SquareMIcon,
    SquareMenuIcon,
    SquareMinusIcon,
    SquareMousePointerIcon,
    SquareParkingIcon,
    SquareParkingOffIcon,
    SquarePauseIcon,
    SquarePenIcon,
    SquarePercentIcon,
    SquarePiIcon,
    SquarePilcrowIcon,
    SquarePlayIcon,
    SquarePlusIcon,
    SquarePowerIcon,
    SquareRadicalIcon,
    SquareRoundCornerIcon,
    SquareScissorsIcon,
    SquareSigmaIcon,
    SquareSlashIcon,
    SquareSplitHorizontalIcon,
    SquareSplitVerticalIcon,
    SquareSquareIcon,
    SquareStackIcon,
    SquareStarIcon,
    SquareStopIcon,
    SquareTerminalIcon,
    SquareUserIcon,
    SquareUserRoundIcon,
    SquareXIcon,
    SquaresExcludeIcon,
    SquaresIntersectIcon,
    SquaresSubtractIcon,
    SquaresUniteIcon,
    SquircleDashedIcon,
    SquircleIcon,
    SquirrelIcon,
    StampIcon,
    StarHalfIcon,
    StarIcon,
    StarOffIcon,
    StepBackIcon,
    StepForwardIcon,
    StethoscopeIcon,
    StickerIcon,
    StickyNoteIcon,
    StoreIcon,
    StretchHorizontalIcon,
    StretchVerticalIcon,
    StrikethroughIcon,
    SubscriptIcon,
    SunDimIcon,
    SunIcon,
    SunMediumIcon,
    SunMoonIcon,
    SunSnowIcon,
    SunriseIcon,
    SunsetIcon,
    SuperscriptIcon,
    SwatchBookIcon,
    SwissFrancIcon,
    SwitchCameraIcon,
    SwordIcon,
    SwordsIcon,
    SyringeIcon,
    Table2Icon,
    TableCellsMergeIcon,
    TableCellsSplitIcon,
    TableColumnsSplitIcon,
    TableIcon,
    TableOfContentsIcon,
    TablePropertiesIcon,
    TableRowsSplitIcon,
    TabletIcon,
    TabletSmartphoneIcon,
    TabletsIcon,
    TagIcon,
    TagsIcon,
    Tally1Icon,
    Tally2Icon,
    Tally3Icon,
    Tally4Icon,
    Tally5Icon,
    TangentIcon,
    TargetIcon,
    TelescopeIcon,
    TentIcon,
    TentTreeIcon,
    TerminalIcon,
    TestTubeDiagonalIcon,
    TestTubeIcon,
    TestTubesIcon,
    TextAlignCenterIcon,
    TextAlignEndIcon,
    TextAlignJustifyIcon,
    TextAlignStartIcon,
    TextCursorIcon,
    TextCursorInputIcon,
    TextInitialIcon,
    TextQuoteIcon,
    TextSearchIcon,
    TextSelectIcon,
    TextWrapIcon,
    TheaterIcon,
    ThermometerIcon,
    ThermometerSnowflakeIcon,
    ThermometerSunIcon,
    ThumbsDownIcon,
    ThumbsUpIcon,
    TicketCheckIcon,
    TicketIcon,
    TicketMinusIcon,
    TicketPercentIcon,
    TicketPlusIcon,
    TicketSlashIcon,
    TicketXIcon,
    TicketsIcon,
    TicketsPlaneIcon,
    TimerIcon,
    TimerOffIcon,
    TimerResetIcon,
    ToggleLeftIcon,
    ToggleRightIcon,
    ToiletIcon,
    ToolCaseIcon,
    TornadoIcon,
    TorusIcon,
    TouchpadIcon,
    TouchpadOffIcon,
    TowerControlIcon,
    ToyBrickIcon,
    TractorIcon,
    TrafficConeIcon,
    TrainFrontIcon,
    TrainFrontTunnelIcon,
    TrainTrackIcon,
    TramFrontIcon,
    TransgenderIcon,
    Trash2Icon,
    TrashIcon,
    TreeDeciduousIcon,
    TreePalmIcon,
    TreePineIcon,
    TreesIcon,
    TrelloIcon,
    TrendingDownIcon,
    TrendingUpDownIcon,
    TrendingUpIcon,
    TriangleAlertIcon,
    TriangleDashedIcon,
    TriangleIcon,
    TriangleRightIcon,
    TrophyIcon,
    TruckElectricIcon,
    TruckIcon,
    TurkishLiraIcon,
    TurntableIcon,
    TurtleIcon,
    TvIcon,
    TvMinimalIcon,
    TvMinimalPlayIcon,
    TwitchIcon,
    TwitterIcon,
    TypeIcon,
    TypeOutlineIcon,
    UmbrellaIcon,
    UmbrellaOffIcon,
    UnderlineIcon,
    Undo2Icon,
    UndoDotIcon,
    UndoIcon,
    UnfoldHorizontalIcon,
    UnfoldVerticalIcon,
    UngroupIcon,
    UniversityIcon,
    Unlink2Icon,
    UnlinkIcon,
    UnplugIcon,
    UploadIcon,
    UsbIcon,
    UserCheckIcon,
    UserCogIcon,
    UserIcon,
    UserLockIcon,
    UserMinusIcon,
    UserPenIcon,
    UserPlusIcon,
    UserRoundCheckIcon,
    UserRoundCogIcon,
    UserRoundIcon,
    UserRoundMinusIcon,
    UserRoundPenIcon,
    UserRoundPlusIcon,
    UserRoundSearchIcon,
    UserRoundXIcon,
    UserSearchIcon,
    UserStarIcon,
    UserXIcon,
    UsersIcon,
    UsersRoundIcon,
    UtensilsCrossedIcon,
    UtensilsIcon,
    UtilityPoleIcon,
    VariableIcon,
    VaultIcon,
    VectorSquareIcon,
    VeganIcon,
    VenetianMaskIcon,
    VenusAndMarsIcon,
    VenusIcon,
    VibrateIcon,
    VibrateOffIcon,
    VideoIcon,
    VideoOffIcon,
    VideotapeIcon,
    ViewIcon,
    VoicemailIcon,
    VolleyballIcon,
    Volume1Icon,
    Volume2Icon,
    VolumeIcon,
    VolumeOffIcon,
    VolumeXIcon,
    VoteIcon,
    WalletCardsIcon,
    WalletIcon,
    WalletMinimalIcon,
    WallpaperIcon,
    WandIcon,
    WandSparklesIcon,
    WarehouseIcon,
    WashingMachineIcon,
    WatchIcon,
    WavesIcon,
    WavesLadderIcon,
    WaypointsIcon,
    WebcamIcon,
    WebhookIcon,
    WebhookOffIcon,
    WeightIcon,
    WheatIcon,
    WheatOffIcon,
    WholeWordIcon,
    WifiCogIcon,
    WifiHighIcon,
    WifiIcon,
    WifiLowIcon,
    WifiOffIcon,
    WifiPenIcon,
    WifiSyncIcon,
    WifiZeroIcon,
    WindArrowDownIcon,
    WindIcon,
    WineIcon,
    WineOffIcon,
    WorkflowIcon,
    WormIcon,
    WrenchIcon,
    XIcon,
    YoutubeIcon,
    ZapIcon,
    ZapOffIcon,
    ZoomInIcon,
    ZoomOutIcon,
} from "lucide-vue-next";

export const Icons = {
    AArrowDown: AArrowDownIcon,
    AArrowUp: AArrowUpIcon,
    ALargeSmall: ALargeSmallIcon,
    Accessibility: AccessibilityIcon,
    Activity: ActivityIcon,
    AirVent: AirVentIcon,
    Airplay: AirplayIcon,
    AlarmClock: AlarmClockIcon,
    AlarmClockCheck: AlarmClockCheckIcon,
    AlarmClockMinus: AlarmClockMinusIcon,
    AlarmClockOff: AlarmClockOffIcon,
    AlarmClockPlus: AlarmClockPlusIcon,
    AlarmSmoke: AlarmSmokeIcon,
    Album: AlbumIcon,
    AlignCenterHorizontal: AlignCenterHorizontalIcon,
    AlignCenterVertical: AlignCenterVerticalIcon,
    AlignEndHorizontal: AlignEndHorizontalIcon,
    AlignEndVertical: AlignEndVerticalIcon,
    AlignHorizontalDistributeCenter: AlignHorizontalDistributeCenterIcon,
    AlignHorizontalDistributeEnd: AlignHorizontalDistributeEndIcon,
    AlignHorizontalDistributeStart: AlignHorizontalDistributeStartIcon,
    AlignHorizontalJustifyCenter: AlignHorizontalJustifyCenterIcon,
    AlignHorizontalJustifyEnd: AlignHorizontalJustifyEndIcon,
    AlignHorizontalJustifyStart: AlignHorizontalJustifyStartIcon,
    AlignHorizontalSpaceAround: AlignHorizontalSpaceAroundIcon,
    AlignHorizontalSpaceBetween: AlignHorizontalSpaceBetweenIcon,
    AlignStartHorizontal: AlignStartHorizontalIcon,
    AlignStartVertical: AlignStartVerticalIcon,
    AlignVerticalDistributeCenter: AlignVerticalDistributeCenterIcon,
    AlignVerticalDistributeEnd: AlignVerticalDistributeEndIcon,
    AlignVerticalDistributeStart: AlignVerticalDistributeStartIcon,
    AlignVerticalJustifyCenter: AlignVerticalJustifyCenterIcon,
    AlignVerticalJustifyEnd: AlignVerticalJustifyEndIcon,
    AlignVerticalJustifyStart: AlignVerticalJustifyStartIcon,
    AlignVerticalSpaceAround: AlignVerticalSpaceAroundIcon,
    AlignVerticalSpaceBetween: AlignVerticalSpaceBetweenIcon,
    Ambulance: AmbulanceIcon,
    Ampersand: AmpersandIcon,
    Ampersands: AmpersandsIcon,
    Amphora: AmphoraIcon,
    Anchor: AnchorIcon,
    Angry: AngryIcon,
    Annoyed: AnnoyedIcon,
    Antenna: AntennaIcon,
    Anvil: AnvilIcon,
    Aperture: ApertureIcon,
    AppWindow: AppWindowIcon,
    AppWindowMac: AppWindowMacIcon,
    Apple: AppleIcon,
    Archive: ArchiveIcon,
    ArchiveRestore: ArchiveRestoreIcon,
    ArchiveX: ArchiveXIcon,
    Armchair: ArmchairIcon,
    ArrowBigDown: ArrowBigDownIcon,
    ArrowBigDownDash: ArrowBigDownDashIcon,
    ArrowBigLeft: ArrowBigLeftIcon,
    ArrowBigLeftDash: ArrowBigLeftDashIcon,
    ArrowBigRight: ArrowBigRightIcon,
    ArrowBigRightDash: ArrowBigRightDashIcon,
    ArrowBigUp: ArrowBigUpIcon,
    ArrowBigUpDash: ArrowBigUpDashIcon,
    ArrowDown: ArrowDownIcon,
    ArrowDown01: ArrowDown01Icon,
    ArrowDown10: ArrowDown10Icon,
    ArrowDownAZ: ArrowDownAZIcon,
    ArrowDownFromLine: ArrowDownFromLineIcon,
    ArrowDownLeft: ArrowDownLeftIcon,
    ArrowDownNarrowWide: ArrowDownNarrowWideIcon,
    ArrowDownRight: ArrowDownRightIcon,
    ArrowDownToDot: ArrowDownToDotIcon,
    ArrowDownToLine: ArrowDownToLineIcon,
    ArrowDownUp: ArrowDownUpIcon,
    ArrowDownWideNarrow: ArrowDownWideNarrowIcon,
    ArrowDownZA: ArrowDownZAIcon,
    ArrowLeft: ArrowLeftIcon,
    ArrowLeftFromLine: ArrowLeftFromLineIcon,
    ArrowLeftRight: ArrowLeftRightIcon,
    ArrowLeftToLine: ArrowLeftToLineIcon,
    ArrowRight: ArrowRightIcon,
    ArrowRightFromLine: ArrowRightFromLineIcon,
    ArrowRightLeft: ArrowRightLeftIcon,
    ArrowRightToLine: ArrowRightToLineIcon,
    ArrowUp: ArrowUpIcon,
    ArrowUp01: ArrowUp01Icon,
    ArrowUp10: ArrowUp10Icon,
    ArrowUpAZ: ArrowUpAZIcon,
    ArrowUpDown: ArrowUpDownIcon,
    ArrowUpFromDot: ArrowUpFromDotIcon,
    ArrowUpFromLine: ArrowUpFromLineIcon,
    ArrowUpLeft: ArrowUpLeftIcon,
    ArrowUpNarrowWide: ArrowUpNarrowWideIcon,
    ArrowUpRight: ArrowUpRightIcon,
    ArrowUpToLine: ArrowUpToLineIcon,
    ArrowUpWideNarrow: ArrowUpWideNarrowIcon,
    ArrowUpZA: ArrowUpZAIcon,
    ArrowsUpFromLine: ArrowsUpFromLineIcon,
    Asterisk: AsteriskIcon,
    AtSign: AtSignIcon,
    Atom: AtomIcon,
    AudioLines: AudioLinesIcon,
    AudioWaveform: AudioWaveformIcon,
    Award: AwardIcon,
    Axe: AxeIcon,
    Axis3d: Axis3dIcon,
    Baby: BabyIcon,
    Backpack: BackpackIcon,
    Badge: BadgeIcon,
    BadgeAlert: BadgeAlertIcon,
    BadgeCent: BadgeCentIcon,
    BadgeCheck: BadgeCheckIcon,
    BadgeDollarSign: BadgeDollarSignIcon,
    BadgeEuro: BadgeEuroIcon,
    BadgeIndianRupee: BadgeIndianRupeeIcon,
    BadgeInfo: BadgeInfoIcon,
    BadgeJapaneseYen: BadgeJapaneseYenIcon,
    BadgeMinus: BadgeMinusIcon,
    BadgePercent: BadgePercentIcon,
    BadgePlus: BadgePlusIcon,
    BadgePoundSterling: BadgePoundSterlingIcon,
    BadgeQuestionMark: BadgeQuestionMarkIcon,
    BadgeRussianRuble: BadgeRussianRubleIcon,
    BadgeSwissFranc: BadgeSwissFrancIcon,
    BadgeTurkishLira: BadgeTurkishLiraIcon,
    BadgeX: BadgeXIcon,
    BaggageClaim: BaggageClaimIcon,
    Ban: BanIcon,
    Banana: BananaIcon,
    Bandage: BandageIcon,
    Banknote: BanknoteIcon,
    BanknoteArrowDown: BanknoteArrowDownIcon,
    BanknoteArrowUp: BanknoteArrowUpIcon,
    BanknoteX: BanknoteXIcon,
    Barcode: BarcodeIcon,
    Barrel: BarrelIcon,
    Baseline: BaselineIcon,
    Bath: BathIcon,
    Battery: BatteryIcon,
    BatteryCharging: BatteryChargingIcon,
    BatteryFull: BatteryFullIcon,
    BatteryLow: BatteryLowIcon,
    BatteryMedium: BatteryMediumIcon,
    BatteryPlus: BatteryPlusIcon,
    BatteryWarning: BatteryWarningIcon,
    Beaker: BeakerIcon,
    Bean: BeanIcon,
    BeanOff: BeanOffIcon,
    Bed: BedIcon,
    BedDouble: BedDoubleIcon,
    BedSingle: BedSingleIcon,
    Beef: BeefIcon,
    Beer: BeerIcon,
    BeerOff: BeerOffIcon,
    Bell: BellIcon,
    BellDot: BellDotIcon,
    BellElectric: BellElectricIcon,
    BellMinus: BellMinusIcon,
    BellOff: BellOffIcon,
    BellPlus: BellPlusIcon,
    BellRing: BellRingIcon,
    BetweenHorizontalEnd: BetweenHorizontalEndIcon,
    BetweenHorizontalStart: BetweenHorizontalStartIcon,
    BetweenVerticalEnd: BetweenVerticalEndIcon,
    BetweenVerticalStart: BetweenVerticalStartIcon,
    BicepsFlexed: BicepsFlexedIcon,
    Bike: BikeIcon,
    Binary: BinaryIcon,
    Binoculars: BinocularsIcon,
    Biohazard: BiohazardIcon,
    Bird: BirdIcon,
    Birdhouse: BirdhouseIcon,
    Bitcoin: BitcoinIcon,
    Blend: BlendIcon,
    Blinds: BlindsIcon,
    Blocks: BlocksIcon,
    Bluetooth: BluetoothIcon,
    BluetoothConnected: BluetoothConnectedIcon,
    BluetoothOff: BluetoothOffIcon,
    BluetoothSearching: BluetoothSearchingIcon,
    Bold: BoldIcon,
    Bolt: BoltIcon,
    Bomb: BombIcon,
    Bone: BoneIcon,
    Book: BookIcon,
    BookA: BookAIcon,
    BookAlert: BookAlertIcon,
    BookAudio: BookAudioIcon,
    BookCheck: BookCheckIcon,
    BookCopy: BookCopyIcon,
    BookDashed: BookDashedIcon,
    BookDown: BookDownIcon,
    BookHeadphones: BookHeadphonesIcon,
    BookHeart: BookHeartIcon,
    BookImage: BookImageIcon,
    BookKey: BookKeyIcon,
    BookLock: BookLockIcon,
    BookMarked: BookMarkedIcon,
    BookMinus: BookMinusIcon,
    BookOpen: BookOpenIcon,
    BookOpenCheck: BookOpenCheckIcon,
    BookOpenText: BookOpenTextIcon,
    BookPlus: BookPlusIcon,
    BookText: BookTextIcon,
    BookType: BookTypeIcon,
    BookUp: BookUpIcon,
    BookUp2: BookUp2Icon,
    BookUser: BookUserIcon,
    BookX: BookXIcon,
    Bookmark: BookmarkIcon,
    BookmarkCheck: BookmarkCheckIcon,
    BookmarkMinus: BookmarkMinusIcon,
    BookmarkPlus: BookmarkPlusIcon,
    BookmarkX: BookmarkXIcon,
    BoomBox: BoomBoxIcon,
    Bot: BotIcon,
    BotMessageSquare: BotMessageSquareIcon,
    BotOff: BotOffIcon,
    BottleWine: BottleWineIcon,
    BowArrow: BowArrowIcon,
    Box: BoxIcon,
    Boxes: BoxesIcon,
    Braces: BracesIcon,
    Brackets: BracketsIcon,
    Brain: BrainIcon,
    BrainCircuit: BrainCircuitIcon,
    BrainCog: BrainCogIcon,
    BrickWall: BrickWallIcon,
    BrickWallFire: BrickWallFireIcon,
    BrickWallShield: BrickWallShieldIcon,
    Briefcase: BriefcaseIcon,
    BriefcaseBusiness: BriefcaseBusinessIcon,
    BriefcaseConveyorBelt: BriefcaseConveyorBeltIcon,
    BriefcaseMedical: BriefcaseMedicalIcon,
    BringToFront: BringToFrontIcon,
    Brush: BrushIcon,
    BrushCleaning: BrushCleaningIcon,
    Bubbles: BubblesIcon,
    Bug: BugIcon,
    BugOff: BugOffIcon,
    BugPlay: BugPlayIcon,
    Building: BuildingIcon,
    Building2: Building2Icon,
    Bus: BusIcon,
    BusFront: BusFrontIcon,
    Cable: CableIcon,
    CableCar: CableCarIcon,
    Cake: CakeIcon,
    CakeSlice: CakeSliceIcon,
    Calculator: CalculatorIcon,
    Calendar: CalendarIcon,
    Calendar1: Calendar1Icon,
    CalendarArrowDown: CalendarArrowDownIcon,
    CalendarArrowUp: CalendarArrowUpIcon,
    CalendarCheck: CalendarCheckIcon,
    CalendarCheck2: CalendarCheck2Icon,
    CalendarClock: CalendarClockIcon,
    CalendarCog: CalendarCogIcon,
    CalendarDays: CalendarDaysIcon,
    CalendarFold: CalendarFoldIcon,
    CalendarHeart: CalendarHeartIcon,
    CalendarMinus: CalendarMinusIcon,
    CalendarMinus2: CalendarMinus2Icon,
    CalendarOff: CalendarOffIcon,
    CalendarPlus: CalendarPlusIcon,
    CalendarPlus2: CalendarPlus2Icon,
    CalendarRange: CalendarRangeIcon,
    CalendarSearch: CalendarSearchIcon,
    CalendarSync: CalendarSyncIcon,
    CalendarX: CalendarXIcon,
    CalendarX2: CalendarX2Icon,
    Camera: CameraIcon,
    CameraOff: CameraOffIcon,
    Candy: CandyIcon,
    CandyCane: CandyCaneIcon,
    CandyOff: CandyOffIcon,
    Cannabis: CannabisIcon,
    Captions: CaptionsIcon,
    CaptionsOff: CaptionsOffIcon,
    Car: CarIcon,
    CarFront: CarFrontIcon,
    CarTaxiFront: CarTaxiFrontIcon,
    Caravan: CaravanIcon,
    CardSim: CardSimIcon,
    Carrot: CarrotIcon,
    CaseLower: CaseLowerIcon,
    CaseSensitive: CaseSensitiveIcon,
    CaseUpper: CaseUpperIcon,
    CassetteTape: CassetteTapeIcon,
    Cast: CastIcon,
    Castle: CastleIcon,
    Cat: CatIcon,
    Cctv: CctvIcon,
    ChartArea: ChartAreaIcon,
    ChartBar: ChartBarIcon,
    ChartBarBig: ChartBarBigIcon,
    ChartBarDecreasing: ChartBarDecreasingIcon,
    ChartBarIncreasing: ChartBarIncreasingIcon,
    ChartBarStacked: ChartBarStackedIcon,
    ChartCandlestick: ChartCandlestickIcon,
    ChartColumn: ChartColumnIcon,
    ChartColumnBig: ChartColumnBigIcon,
    ChartColumnDecreasing: ChartColumnDecreasingIcon,
    ChartColumnIncreasing: ChartColumnIncreasingIcon,
    ChartColumnStacked: ChartColumnStackedIcon,
    ChartGantt: ChartGanttIcon,
    ChartLine: ChartLineIcon,
    ChartNetwork: ChartNetworkIcon,
    ChartNoAxesColumn: ChartNoAxesColumnIcon,
    ChartNoAxesColumnDecreasing: ChartNoAxesColumnDecreasingIcon,
    ChartNoAxesColumnIncreasing: ChartNoAxesColumnIncreasingIcon,
    ChartNoAxesCombined: ChartNoAxesCombinedIcon,
    ChartNoAxesGantt: ChartNoAxesGanttIcon,
    ChartPie: ChartPieIcon,
    ChartScatter: ChartScatterIcon,
    ChartSpline: ChartSplineIcon,
    Check: CheckIcon,
    CheckCheck: CheckCheckIcon,
    CheckLine: CheckLineIcon,
    ChefHat: ChefHatIcon,
    Cherry: CherryIcon,
    ChessBishop: ChessBishopIcon,
    ChessKing: ChessKingIcon,
    ChessKnight: ChessKnightIcon,
    ChessPawn: ChessPawnIcon,
    ChessQueen: ChessQueenIcon,
    ChessRook: ChessRookIcon,
    ChevronDown: ChevronDownIcon,
    ChevronFirst: ChevronFirstIcon,
    ChevronLast: ChevronLastIcon,
    ChevronLeft: ChevronLeftIcon,
    ChevronRight: ChevronRightIcon,
    ChevronUp: ChevronUpIcon,
    ChevronsDown: ChevronsDownIcon,
    ChevronsDownUp: ChevronsDownUpIcon,
    ChevronsLeft: ChevronsLeftIcon,
    ChevronsLeftRight: ChevronsLeftRightIcon,
    ChevronsLeftRightEllipsis: ChevronsLeftRightEllipsisIcon,
    ChevronsRight: ChevronsRightIcon,
    ChevronsRightLeft: ChevronsRightLeftIcon,
    ChevronsUp: ChevronsUpIcon,
    ChevronsUpDown: ChevronsUpDownIcon,
    Chromium: ChromiumIcon,
    Church: ChurchIcon,
    Cigarette: CigaretteIcon,
    CigaretteOff: CigaretteOffIcon,
    Circle: CircleIcon,
    CircleAlert: CircleAlertIcon,
    CircleArrowDown: CircleArrowDownIcon,
    CircleArrowLeft: CircleArrowLeftIcon,
    CircleArrowOutDownLeft: CircleArrowOutDownLeftIcon,
    CircleArrowOutDownRight: CircleArrowOutDownRightIcon,
    CircleArrowOutUpLeft: CircleArrowOutUpLeftIcon,
    CircleArrowOutUpRight: CircleArrowOutUpRightIcon,
    CircleArrowRight: CircleArrowRightIcon,
    CircleArrowUp: CircleArrowUpIcon,
    CircleCheck: CircleCheckIcon,
    CircleCheckBig: CircleCheckBigIcon,
    CircleChevronDown: CircleChevronDownIcon,
    CircleChevronLeft: CircleChevronLeftIcon,
    CircleChevronRight: CircleChevronRightIcon,
    CircleChevronUp: CircleChevronUpIcon,
    CircleDashed: CircleDashedIcon,
    CircleDivide: CircleDivideIcon,
    CircleDollarSign: CircleDollarSignIcon,
    CircleDot: CircleDotIcon,
    CircleDotDashed: CircleDotDashedIcon,
    CircleEllipsis: CircleEllipsisIcon,
    CircleEqual: CircleEqualIcon,
    CircleFadingArrowUp: CircleFadingArrowUpIcon,
    CircleFadingPlus: CircleFadingPlusIcon,
    CircleGauge: CircleGaugeIcon,
    CircleMinus: CircleMinusIcon,
    CircleOff: CircleOffIcon,
    CircleParking: CircleParkingIcon,
    CircleParkingOff: CircleParkingOffIcon,
    CirclePause: CirclePauseIcon,
    CirclePercent: CirclePercentIcon,
    CirclePlay: CirclePlayIcon,
    CirclePlus: CirclePlusIcon,
    CirclePoundSterling: CirclePoundSterlingIcon,
    CirclePower: CirclePowerIcon,
    CircleQuestionMark: CircleQuestionMarkIcon,
    CircleSlash: CircleSlashIcon,
    CircleSlash2: CircleSlash2Icon,
    CircleSmall: CircleSmallIcon,
    CircleStar: CircleStarIcon,
    CircleStop: CircleStopIcon,
    CircleUser: CircleUserIcon,
    CircleUserRound: CircleUserRoundIcon,
    CircleX: CircleXIcon,
    CircuitBoard: CircuitBoardIcon,
    Citrus: CitrusIcon,
    Clapperboard: ClapperboardIcon,
    Clipboard: ClipboardIcon,
    ClipboardCheck: ClipboardCheckIcon,
    ClipboardClock: ClipboardClockIcon,
    ClipboardCopy: ClipboardCopyIcon,
    ClipboardList: ClipboardListIcon,
    ClipboardMinus: ClipboardMinusIcon,
    ClipboardPaste: ClipboardPasteIcon,
    ClipboardPen: ClipboardPenIcon,
    ClipboardPenLine: ClipboardPenLineIcon,
    ClipboardPlus: ClipboardPlusIcon,
    ClipboardType: ClipboardTypeIcon,
    ClipboardX: ClipboardXIcon,
    Clock: ClockIcon,
    Clock1: Clock1Icon,
    Clock10: Clock10Icon,
    Clock11: Clock11Icon,
    Clock12: Clock12Icon,
    Clock2: Clock2Icon,
    Clock3: Clock3Icon,
    Clock4: Clock4Icon,
    Clock5: Clock5Icon,
    Clock6: Clock6Icon,
    Clock7: Clock7Icon,
    Clock8: Clock8Icon,
    Clock9: Clock9Icon,
    ClockAlert: ClockAlertIcon,
    ClockArrowDown: ClockArrowDownIcon,
    ClockArrowUp: ClockArrowUpIcon,
    ClockCheck: ClockCheckIcon,
    ClockFading: ClockFadingIcon,
    ClockPlus: ClockPlusIcon,
    ClosedCaption: ClosedCaptionIcon,
    Cloud: CloudIcon,
    CloudAlert: CloudAlertIcon,
    CloudCheck: CloudCheckIcon,
    CloudCog: CloudCogIcon,
    CloudDownload: CloudDownloadIcon,
    CloudDrizzle: CloudDrizzleIcon,
    CloudFog: CloudFogIcon,
    CloudHail: CloudHailIcon,
    CloudLightning: CloudLightningIcon,
    CloudMoon: CloudMoonIcon,
    CloudMoonRain: CloudMoonRainIcon,
    CloudOff: CloudOffIcon,
    CloudRain: CloudRainIcon,
    CloudRainWind: CloudRainWindIcon,
    CloudSnow: CloudSnowIcon,
    CloudSun: CloudSunIcon,
    CloudSunRain: CloudSunRainIcon,
    CloudUpload: CloudUploadIcon,
    Cloudy: CloudyIcon,
    Clover: CloverIcon,
    Club: ClubIcon,
    Code: CodeIcon,
    CodeXml: CodeXmlIcon,
    Codepen: CodepenIcon,
    Codesandbox: CodesandboxIcon,
    Coffee: CoffeeIcon,
    Cog: CogIcon,
    Coins: CoinsIcon,
    Columns2: Columns2Icon,
    Columns3: Columns3Icon,
    Columns3Cog: Columns3CogIcon,
    Columns4: Columns4Icon,
    Combine: CombineIcon,
    Command: CommandIcon,
    Compass: CompassIcon,
    Component: ComponentIcon,
    Computer: ComputerIcon,
    ConciergeBell: ConciergeBellIcon,
    Cone: ConeIcon,
    Construction: ConstructionIcon,
    Contact: ContactIcon,
    ContactRound: ContactRoundIcon,
    Container: ContainerIcon,
    Contrast: ContrastIcon,
    Cookie: CookieIcon,
    CookingPot: CookingPotIcon,
    Copy: CopyIcon,
    CopyCheck: CopyCheckIcon,
    CopyMinus: CopyMinusIcon,
    CopyPlus: CopyPlusIcon,
    CopySlash: CopySlashIcon,
    CopyX: CopyXIcon,
    Copyleft: CopyleftIcon,
    Copyright: CopyrightIcon,
    CornerDownLeft: CornerDownLeftIcon,
    CornerDownRight: CornerDownRightIcon,
    CornerLeftDown: CornerLeftDownIcon,
    CornerLeftUp: CornerLeftUpIcon,
    CornerRightDown: CornerRightDownIcon,
    CornerRightUp: CornerRightUpIcon,
    CornerUpLeft: CornerUpLeftIcon,
    CornerUpRight: CornerUpRightIcon,
    Cpu: CpuIcon,
    CreativeCommons: CreativeCommonsIcon,
    CreditCard: CreditCardIcon,
    Croissant: CroissantIcon,
    Crop: CropIcon,
    Cross: CrossIcon,
    Crosshair: CrosshairIcon,
    Crown: CrownIcon,
    Cuboid: CuboidIcon,
    CupSoda: CupSodaIcon,
    Currency: CurrencyIcon,
    Cylinder: CylinderIcon,
    Dam: DamIcon,
    Database: DatabaseIcon,
    DatabaseBackup: DatabaseBackupIcon,
    DatabaseZap: DatabaseZapIcon,
    DecimalsArrowLeft: DecimalsArrowLeftIcon,
    DecimalsArrowRight: DecimalsArrowRightIcon,
    Delete: DeleteIcon,
    Dessert: DessertIcon,
    Diameter: DiameterIcon,
    Diamond: DiamondIcon,
    DiamondMinus: DiamondMinusIcon,
    DiamondPercent: DiamondPercentIcon,
    DiamondPlus: DiamondPlusIcon,
    Dice1: Dice1Icon,
    Dice2: Dice2Icon,
    Dice3: Dice3Icon,
    Dice4: Dice4Icon,
    Dice5: Dice5Icon,
    Dice6: Dice6Icon,
    Dices: DicesIcon,
    Diff: DiffIcon,
    Disc: DiscIcon,
    Disc2: Disc2Icon,
    Disc3: Disc3Icon,
    DiscAlbum: DiscAlbumIcon,
    Divide: DivideIcon,
    Dna: DnaIcon,
    DnaOff: DnaOffIcon,
    Dock: DockIcon,
    Dog: DogIcon,
    DollarSign: DollarSignIcon,
    Donut: DonutIcon,
    DoorClosed: DoorClosedIcon,
    DoorClosedLocked: DoorClosedLockedIcon,
    DoorOpen: DoorOpenIcon,
    Dot: DotIcon,
    Download: DownloadIcon,
    DraftingCompass: DraftingCompassIcon,
    Drama: DramaIcon,
    Dribbble: DribbbleIcon,
    Drill: DrillIcon,
    Drone: DroneIcon,
    Droplet: DropletIcon,
    DropletOff: DropletOffIcon,
    Droplets: DropletsIcon,
    Drum: DrumIcon,
    Drumstick: DrumstickIcon,
    Dumbbell: DumbbellIcon,
    Ear: EarIcon,
    EarOff: EarOffIcon,
    Earth: EarthIcon,
    EarthLock: EarthLockIcon,
    Eclipse: EclipseIcon,
    Egg: EggIcon,
    EggFried: EggFriedIcon,
    EggOff: EggOffIcon,
    Ellipsis: EllipsisIcon,
    EllipsisVertical: EllipsisVerticalIcon,
    Equal: EqualIcon,
    EqualApproximately: EqualApproximatelyIcon,
    EqualNot: EqualNotIcon,
    Eraser: EraserIcon,
    EthernetPort: EthernetPortIcon,
    Euro: EuroIcon,
    EvCharger: EvChargerIcon,
    Expand: ExpandIcon,
    ExternalLink: ExternalLinkIcon,
    Eye: EyeIcon,
    EyeClosed: EyeClosedIcon,
    EyeOff: EyeOffIcon,
    Facebook: FacebookIcon,
    Factory: FactoryIcon,
    Fan: FanIcon,
    FastForward: FastForwardIcon,
    Feather: FeatherIcon,
    Fence: FenceIcon,
    FerrisWheel: FerrisWheelIcon,
    Figma: FigmaIcon,
    File: FileIcon,
    FileArchive: FileArchiveIcon,
    FileAxis3d: FileAxis3dIcon,
    FileBadge: FileBadgeIcon,
    FileBox: FileBoxIcon,
    FileBraces: FileBracesIcon,
    FileBracesCorner: FileBracesCornerIcon,
    FileChartColumn: FileChartColumnIcon,
    FileChartColumnIncreasing: FileChartColumnIncreasingIcon,
    FileChartLine: FileChartLineIcon,
    FileChartPie: FileChartPieIcon,
    FileCheck: FileCheckIcon,
    FileCheckCorner: FileCheckCornerIcon,
    FileClock: FileClockIcon,
    FileCode: FileCodeIcon,
    FileCodeCorner: FileCodeCornerIcon,
    FileCog: FileCogIcon,
    FileDiff: FileDiffIcon,
    FileDigit: FileDigitIcon,
    FileDown: FileDownIcon,
    FileExclamationPoint: FileExclamationPointIcon,
    FileHeadphone: FileHeadphoneIcon,
    FileHeart: FileHeartIcon,
    FileImage: FileImageIcon,
    FileInput: FileInputIcon,
    FileKey: FileKeyIcon,
    FileLock: FileLockIcon,
    FileMinus: FileMinusIcon,
    FileMinusCorner: FileMinusCornerIcon,
    FileMusic: FileMusicIcon,
    FileOutput: FileOutputIcon,
    FilePen: FilePenIcon,
    FilePenLine: FilePenLineIcon,
    FilePlay: FilePlayIcon,
    FilePlus: FilePlusIcon,
    FilePlusCorner: FilePlusCornerIcon,
    FileQuestionMark: FileQuestionMarkIcon,
    FileScan: FileScanIcon,
    FileSearch: FileSearchIcon,
    FileSearchCorner: FileSearchCornerIcon,
    FileSignal: FileSignalIcon,
    FileSliders: FileSlidersIcon,
    FileSpreadsheet: FileSpreadsheetIcon,
    FileStack: FileStackIcon,
    FileSymlink: FileSymlinkIcon,
    FileTerminal: FileTerminalIcon,
    FileText: FileTextIcon,
    FileType: FileTypeIcon,
    FileTypeCorner: FileTypeCornerIcon,
    FileUp: FileUpIcon,
    FileUser: FileUserIcon,
    FileVideoCamera: FileVideoCameraIcon,
    FileVolume: FileVolumeIcon,
    FileX: FileXIcon,
    FileXCorner: FileXCornerIcon,
    Files: FilesIcon,
    Film: FilmIcon,
    Fingerprint: FingerprintIcon,
    FireExtinguisher: FireExtinguisherIcon,
    Fish: FishIcon,
    FishOff: FishOffIcon,
    FishSymbol: FishSymbolIcon,
    Flag: FlagIcon,
    FlagOff: FlagOffIcon,
    FlagTriangleLeft: FlagTriangleLeftIcon,
    FlagTriangleRight: FlagTriangleRightIcon,
    Flame: FlameIcon,
    FlameKindling: FlameKindlingIcon,
    Flashlight: FlashlightIcon,
    FlashlightOff: FlashlightOffIcon,
    FlaskConical: FlaskConicalIcon,
    FlaskConicalOff: FlaskConicalOffIcon,
    FlaskRound: FlaskRoundIcon,
    FlipHorizontal: FlipHorizontalIcon,
    FlipHorizontal2: FlipHorizontal2Icon,
    FlipVertical: FlipVerticalIcon,
    FlipVertical2: FlipVertical2Icon,
    Flower: FlowerIcon,
    Flower2: Flower2Icon,
    Focus: FocusIcon,
    FoldHorizontal: FoldHorizontalIcon,
    FoldVertical: FoldVerticalIcon,
    Folder: FolderIcon,
    FolderArchive: FolderArchiveIcon,
    FolderCheck: FolderCheckIcon,
    FolderClock: FolderClockIcon,
    FolderClosed: FolderClosedIcon,
    FolderCode: FolderCodeIcon,
    FolderCog: FolderCogIcon,
    FolderDot: FolderDotIcon,
    FolderDown: FolderDownIcon,
    FolderGit: FolderGitIcon,
    FolderGit2: FolderGit2Icon,
    FolderHeart: FolderHeartIcon,
    FolderInput: FolderInputIcon,
    FolderKanban: FolderKanbanIcon,
    FolderKey: FolderKeyIcon,
    FolderLock: FolderLockIcon,
    FolderMinus: FolderMinusIcon,
    FolderOpen: FolderOpenIcon,
    FolderOpenDot: FolderOpenDotIcon,
    FolderOutput: FolderOutputIcon,
    FolderPen: FolderPenIcon,
    FolderPlus: FolderPlusIcon,
    FolderRoot: FolderRootIcon,
    FolderSearch: FolderSearchIcon,
    FolderSearch2: FolderSearch2Icon,
    FolderSymlink: FolderSymlinkIcon,
    FolderSync: FolderSyncIcon,
    FolderTree: FolderTreeIcon,
    FolderUp: FolderUpIcon,
    FolderX: FolderXIcon,
    Folders: FoldersIcon,
    Footprints: FootprintsIcon,
    Forklift: ForkliftIcon,
    Forward: ForwardIcon,
    Frame: FrameIcon,
    Framer: FramerIcon,
    Frown: FrownIcon,
    Fuel: FuelIcon,
    Fullscreen: FullscreenIcon,
    Funnel: FunnelIcon,
    FunnelPlus: FunnelPlusIcon,
    FunnelX: FunnelXIcon,
    GalleryHorizontal: GalleryHorizontalIcon,
    GalleryHorizontalEnd: GalleryHorizontalEndIcon,
    GalleryThumbnails: GalleryThumbnailsIcon,
    GalleryVertical: GalleryVerticalIcon,
    GalleryVerticalEnd: GalleryVerticalEndIcon,
    Gamepad: GamepadIcon,
    Gamepad2: Gamepad2Icon,
    GamepadDirectional: GamepadDirectionalIcon,
    Gauge: GaugeIcon,
    Gavel: GavelIcon,
    Gem: GemIcon,
    GeorgianLari: GeorgianLariIcon,
    Ghost: GhostIcon,
    Gift: GiftIcon,
    GitBranch: GitBranchIcon,
    GitBranchMinus: GitBranchMinusIcon,
    GitBranchPlus: GitBranchPlusIcon,
    GitCommitHorizontal: GitCommitHorizontalIcon,
    GitCommitVertical: GitCommitVerticalIcon,
    GitCompare: GitCompareIcon,
    GitCompareArrows: GitCompareArrowsIcon,
    GitFork: GitForkIcon,
    GitGraph: GitGraphIcon,
    GitMerge: GitMergeIcon,
    GitPullRequest: GitPullRequestIcon,
    GitPullRequestArrow: GitPullRequestArrowIcon,
    GitPullRequestClosed: GitPullRequestClosedIcon,
    GitPullRequestCreate: GitPullRequestCreateIcon,
    GitPullRequestCreateArrow: GitPullRequestCreateArrowIcon,
    GitPullRequestDraft: GitPullRequestDraftIcon,
    Github: GithubIcon,
    Gitlab: GitlabIcon,
    GlassWater: GlassWaterIcon,
    Glasses: GlassesIcon,
    Globe: GlobeIcon,
    GlobeLock: GlobeLockIcon,
    Goal: GoalIcon,
    Gpu: GpuIcon,
    GraduationCap: GraduationCapIcon,
    Grape: GrapeIcon,
    Grid2x2: Grid2x2Icon,
    Grid2x2Check: Grid2x2CheckIcon,
    Grid2x2Plus: Grid2x2PlusIcon,
    Grid2x2X: Grid2x2XIcon,
    Grid3x2: Grid3x2Icon,
    Grid3x3: Grid3x3Icon,
    Grip: GripIcon,
    GripHorizontal: GripHorizontalIcon,
    GripVertical: GripVerticalIcon,
    Group: GroupIcon,
    Guitar: GuitarIcon,
    Ham: HamIcon,
    Hamburger: HamburgerIcon,
    Hammer: HammerIcon,
    Hand: HandIcon,
    HandCoins: HandCoinsIcon,
    HandFist: HandFistIcon,
    HandGrab: HandGrabIcon,
    HandHeart: HandHeartIcon,
    HandHelping: HandHelpingIcon,
    HandMetal: HandMetalIcon,
    HandPlatter: HandPlatterIcon,
    Handbag: HandbagIcon,
    Handshake: HandshakeIcon,
    HardDrive: HardDriveIcon,
    HardDriveDownload: HardDriveDownloadIcon,
    HardDriveUpload: HardDriveUploadIcon,
    HardHat: HardHatIcon,
    Hash: HashIcon,
    HatGlasses: HatGlassesIcon,
    Haze: HazeIcon,
    HdmiPort: HdmiPortIcon,
    Heading: HeadingIcon,
    Heading1: Heading1Icon,
    Heading2: Heading2Icon,
    Heading3: Heading3Icon,
    Heading4: Heading4Icon,
    Heading5: Heading5Icon,
    Heading6: Heading6Icon,
    HeadphoneOff: HeadphoneOffIcon,
    Headphones: HeadphonesIcon,
    Headset: HeadsetIcon,
    Heart: HeartIcon,
    HeartCrack: HeartCrackIcon,
    HeartHandshake: HeartHandshakeIcon,
    HeartMinus: HeartMinusIcon,
    HeartOff: HeartOffIcon,
    HeartPlus: HeartPlusIcon,
    HeartPulse: HeartPulseIcon,
    Heater: HeaterIcon,
    Helicopter: HelicopterIcon,
    Hexagon: HexagonIcon,
    Highlighter: HighlighterIcon,
    History: HistoryIcon,
    Hop: HopIcon,
    HopOff: HopOffIcon,
    Hospital: HospitalIcon,
    Hotel: HotelIcon,
    Hourglass: HourglassIcon,
    House: HouseIcon,
    HouseHeart: HouseHeartIcon,
    HousePlug: HousePlugIcon,
    HousePlus: HousePlusIcon,
    HouseWifi: HouseWifiIcon,
    IceCreamBowl: IceCreamBowlIcon,
    IceCreamCone: IceCreamConeIcon,
    IdCard: IdCardIcon,
    IdCardLanyard: IdCardLanyardIcon,
    Image: ImageIcon,
    ImageDown: ImageDownIcon,
    ImageMinus: ImageMinusIcon,
    ImageOff: ImageOffIcon,
    ImagePlay: ImagePlayIcon,
    ImagePlus: ImagePlusIcon,
    ImageUp: ImageUpIcon,
    ImageUpscale: ImageUpscaleIcon,
    Images: ImagesIcon,
    Import: ImportIcon,
    Inbox: InboxIcon,
    IndianRupee: IndianRupeeIcon,
    Infinity: InfinityIcon,
    Info: InfoIcon,
    InspectionPanel: InspectionPanelIcon,
    Instagram: InstagramIcon,
    Italic: ItalicIcon,
    IterationCcw: IterationCcwIcon,
    IterationCw: IterationCwIcon,
    JapaneseYen: JapaneseYenIcon,
    Joystick: JoystickIcon,
    Kanban: KanbanIcon,
    Kayak: KayakIcon,
    Key: KeyIcon,
    KeyRound: KeyRoundIcon,
    KeySquare: KeySquareIcon,
    Keyboard: KeyboardIcon,
    KeyboardMusic: KeyboardMusicIcon,
    KeyboardOff: KeyboardOffIcon,
    Lamp: LampIcon,
    LampCeiling: LampCeilingIcon,
    LampDesk: LampDeskIcon,
    LampFloor: LampFloorIcon,
    LampWallDown: LampWallDownIcon,
    LampWallUp: LampWallUpIcon,
    LandPlot: LandPlotIcon,
    Landmark: LandmarkIcon,
    Languages: LanguagesIcon,
    Laptop: LaptopIcon,
    LaptopMinimal: LaptopMinimalIcon,
    LaptopMinimalCheck: LaptopMinimalCheckIcon,
    Lasso: LassoIcon,
    LassoSelect: LassoSelectIcon,
    Laugh: LaughIcon,
    Layers: LayersIcon,
    Layers2: Layers2Icon,
    LayoutDashboard: LayoutDashboardIcon,
    LayoutGrid: LayoutGridIcon,
    LayoutList: LayoutListIcon,
    LayoutPanelLeft: LayoutPanelLeftIcon,
    LayoutPanelTop: LayoutPanelTopIcon,
    LayoutTemplate: LayoutTemplateIcon,
    Leaf: LeafIcon,
    LeafyGreen: LeafyGreenIcon,
    Lectern: LecternIcon,
    Library: LibraryIcon,
    LibraryBig: LibraryBigIcon,
    LifeBuoy: LifeBuoyIcon,
    Ligature: LigatureIcon,
    Lightbulb: LightbulbIcon,
    LightbulbOff: LightbulbOffIcon,
    LineSquiggle: LineSquiggleIcon,
    Link: LinkIcon,
    Link2: Link2Icon,
    Link2Off: Link2OffIcon,
    Linkedin: LinkedinIcon,
    List: ListIcon,
    ListCheck: ListCheckIcon,
    ListChecks: ListChecksIcon,
    ListChevronsDownUp: ListChevronsDownUpIcon,
    ListChevronsUpDown: ListChevronsUpDownIcon,
    ListCollapse: ListCollapseIcon,
    ListEnd: ListEndIcon,
    ListFilter: ListFilterIcon,
    ListFilterPlus: ListFilterPlusIcon,
    ListIndentDecrease: ListIndentDecreaseIcon,
    ListIndentIncrease: ListIndentIncreaseIcon,
    ListMinus: ListMinusIcon,
    ListMusic: ListMusicIcon,
    ListOrdered: ListOrderedIcon,
    ListPlus: ListPlusIcon,
    ListRestart: ListRestartIcon,
    ListStart: ListStartIcon,
    ListTodo: ListTodoIcon,
    ListTree: ListTreeIcon,
    ListVideo: ListVideoIcon,
    ListX: ListXIcon,
    Loader: LoaderIcon,
    LoaderCircle: LoaderCircleIcon,
    LoaderPinwheel: LoaderPinwheelIcon,
    Locate: LocateIcon,
    LocateFixed: LocateFixedIcon,
    LocateOff: LocateOffIcon,
    Lock: LockIcon,
    LockKeyhole: LockKeyholeIcon,
    LockKeyholeOpen: LockKeyholeOpenIcon,
    LockOpen: LockOpenIcon,
    LogIn: LogInIcon,
    LogOut: LogOutIcon,
    Logs: LogsIcon,
    Lollipop: LollipopIcon,
    Luggage: LuggageIcon,
    Magnet: MagnetIcon,
    Mail: MailIcon,
    MailCheck: MailCheckIcon,
    MailMinus: MailMinusIcon,
    MailOpen: MailOpenIcon,
    MailPlus: MailPlusIcon,
    MailQuestionMark: MailQuestionMarkIcon,
    MailSearch: MailSearchIcon,
    MailWarning: MailWarningIcon,
    MailX: MailXIcon,
    Mailbox: MailboxIcon,
    Mails: MailsIcon,
    Map: MapIcon,
    MapMinus: MapMinusIcon,
    MapPin: MapPinIcon,
    MapPinCheck: MapPinCheckIcon,
    MapPinCheckInside: MapPinCheckInsideIcon,
    MapPinHouse: MapPinHouseIcon,
    MapPinMinus: MapPinMinusIcon,
    MapPinMinusInside: MapPinMinusInsideIcon,
    MapPinOff: MapPinOffIcon,
    MapPinPen: MapPinPenIcon,
    MapPinPlus: MapPinPlusIcon,
    MapPinPlusInside: MapPinPlusInsideIcon,
    MapPinX: MapPinXIcon,
    MapPinXInside: MapPinXInsideIcon,
    MapPinned: MapPinnedIcon,
    MapPlus: MapPlusIcon,
    Mars: MarsIcon,
    MarsStroke: MarsStrokeIcon,
    Martini: MartiniIcon,
    Maximize: MaximizeIcon,
    Maximize2: Maximize2Icon,
    Medal: MedalIcon,
    Megaphone: MegaphoneIcon,
    MegaphoneOff: MegaphoneOffIcon,
    Meh: MehIcon,
    MemoryStick: MemoryStickIcon,
    Menu: MenuIcon,
    Merge: MergeIcon,
    MessageCircle: MessageCircleIcon,
    MessageCircleCode: MessageCircleCodeIcon,
    MessageCircleDashed: MessageCircleDashedIcon,
    MessageCircleHeart: MessageCircleHeartIcon,
    MessageCircleMore: MessageCircleMoreIcon,
    MessageCircleOff: MessageCircleOffIcon,
    MessageCirclePlus: MessageCirclePlusIcon,
    MessageCircleQuestionMark: MessageCircleQuestionMarkIcon,
    MessageCircleReply: MessageCircleReplyIcon,
    MessageCircleWarning: MessageCircleWarningIcon,
    MessageCircleX: MessageCircleXIcon,
    MessageSquare: MessageSquareIcon,
    MessageSquareCode: MessageSquareCodeIcon,
    MessageSquareDashed: MessageSquareDashedIcon,
    MessageSquareDiff: MessageSquareDiffIcon,
    MessageSquareDot: MessageSquareDotIcon,
    MessageSquareHeart: MessageSquareHeartIcon,
    MessageSquareLock: MessageSquareLockIcon,
    MessageSquareMore: MessageSquareMoreIcon,
    MessageSquareOff: MessageSquareOffIcon,
    MessageSquarePlus: MessageSquarePlusIcon,
    MessageSquareQuote: MessageSquareQuoteIcon,
    MessageSquareReply: MessageSquareReplyIcon,
    MessageSquareShare: MessageSquareShareIcon,
    MessageSquareText: MessageSquareTextIcon,
    MessageSquareWarning: MessageSquareWarningIcon,
    MessageSquareX: MessageSquareXIcon,
    MessagesSquare: MessagesSquareIcon,
    Mic: MicIcon,
    MicOff: MicOffIcon,
    MicVocal: MicVocalIcon,
    Microchip: MicrochipIcon,
    Microscope: MicroscopeIcon,
    Microwave: MicrowaveIcon,
    Milestone: MilestoneIcon,
    Milk: MilkIcon,
    MilkOff: MilkOffIcon,
    Minimize: MinimizeIcon,
    Minimize2: Minimize2Icon,
    Minus: MinusIcon,
    Monitor: MonitorIcon,
    MonitorCheck: MonitorCheckIcon,
    MonitorCloud: MonitorCloudIcon,
    MonitorCog: MonitorCogIcon,
    MonitorDot: MonitorDotIcon,
    MonitorDown: MonitorDownIcon,
    MonitorOff: MonitorOffIcon,
    MonitorPause: MonitorPauseIcon,
    MonitorPlay: MonitorPlayIcon,
    MonitorSmartphone: MonitorSmartphoneIcon,
    MonitorSpeaker: MonitorSpeakerIcon,
    MonitorStop: MonitorStopIcon,
    MonitorUp: MonitorUpIcon,
    MonitorX: MonitorXIcon,
    Moon: MoonIcon,
    MoonStar: MoonStarIcon,
    Motorbike: MotorbikeIcon,
    Mountain: MountainIcon,
    MountainSnow: MountainSnowIcon,
    Mouse: MouseIcon,
    MouseOff: MouseOffIcon,
    MousePointer: MousePointerIcon,
    MousePointer2: MousePointer2Icon,
    MousePointer2Off: MousePointer2OffIcon,
    MousePointerBan: MousePointerBanIcon,
    MousePointerClick: MousePointerClickIcon,
    Move: MoveIcon,
    Move3d: Move3dIcon,
    MoveDiagonal: MoveDiagonalIcon,
    MoveDiagonal2: MoveDiagonal2Icon,
    MoveDown: MoveDownIcon,
    MoveDownLeft: MoveDownLeftIcon,
    MoveDownRight: MoveDownRightIcon,
    MoveHorizontal: MoveHorizontalIcon,
    MoveLeft: MoveLeftIcon,
    MoveRight: MoveRightIcon,
    MoveUp: MoveUpIcon,
    MoveUpLeft: MoveUpLeftIcon,
    MoveUpRight: MoveUpRightIcon,
    MoveVertical: MoveVerticalIcon,
    Music: MusicIcon,
    Music2: Music2Icon,
    Music3: Music3Icon,
    Music4: Music4Icon,
    Navigation: NavigationIcon,
    Navigation2: Navigation2Icon,
    Navigation2Off: Navigation2OffIcon,
    NavigationOff: NavigationOffIcon,
    Network: NetworkIcon,
    Newspaper: NewspaperIcon,
    Nfc: NfcIcon,
    NonBinary: NonBinaryIcon,
    Notebook: NotebookIcon,
    NotebookPen: NotebookPenIcon,
    NotebookTabs: NotebookTabsIcon,
    NotebookText: NotebookTextIcon,
    NotepadText: NotepadTextIcon,
    NotepadTextDashed: NotepadTextDashedIcon,
    Nut: NutIcon,
    NutOff: NutOffIcon,
    Octagon: OctagonIcon,
    OctagonAlert: OctagonAlertIcon,
    OctagonMinus: OctagonMinusIcon,
    OctagonPause: OctagonPauseIcon,
    OctagonX: OctagonXIcon,
    Omega: OmegaIcon,
    Option: OptionIcon,
    Orbit: OrbitIcon,
    Origami: OrigamiIcon,
    Package: PackageIcon,
    Package2: Package2Icon,
    PackageCheck: PackageCheckIcon,
    PackageMinus: PackageMinusIcon,
    PackageOpen: PackageOpenIcon,
    PackagePlus: PackagePlusIcon,
    PackageSearch: PackageSearchIcon,
    PackageX: PackageXIcon,
    PaintBucket: PaintBucketIcon,
    PaintRoller: PaintRollerIcon,
    Paintbrush: PaintbrushIcon,
    PaintbrushVertical: PaintbrushVerticalIcon,
    Palette: PaletteIcon,
    Panda: PandaIcon,
    PanelBottom: PanelBottomIcon,
    PanelBottomClose: PanelBottomCloseIcon,
    PanelBottomDashed: PanelBottomDashedIcon,
    PanelBottomOpen: PanelBottomOpenIcon,
    PanelLeft: PanelLeftIcon,
    PanelLeftClose: PanelLeftCloseIcon,
    PanelLeftDashed: PanelLeftDashedIcon,
    PanelLeftOpen: PanelLeftOpenIcon,
    PanelLeftRightDashed: PanelLeftRightDashedIcon,
    PanelRight: PanelRightIcon,
    PanelRightClose: PanelRightCloseIcon,
    PanelRightDashed: PanelRightDashedIcon,
    PanelRightOpen: PanelRightOpenIcon,
    PanelTop: PanelTopIcon,
    PanelTopBottomDashed: PanelTopBottomDashedIcon,
    PanelTopClose: PanelTopCloseIcon,
    PanelTopDashed: PanelTopDashedIcon,
    PanelTopOpen: PanelTopOpenIcon,
    PanelsLeftBottom: PanelsLeftBottomIcon,
    PanelsRightBottom: PanelsRightBottomIcon,
    PanelsTopLeft: PanelsTopLeftIcon,
    Paperclip: PaperclipIcon,
    Parentheses: ParenthesesIcon,
    ParkingMeter: ParkingMeterIcon,
    PartyPopper: PartyPopperIcon,
    Pause: PauseIcon,
    PawPrint: PawPrintIcon,
    PcCase: PcCaseIcon,
    Pen: PenIcon,
    PenLine: PenLineIcon,
    PenOff: PenOffIcon,
    PenTool: PenToolIcon,
    Pencil: PencilIcon,
    PencilLine: PencilLineIcon,
    PencilOff: PencilOffIcon,
    PencilRuler: PencilRulerIcon,
    Pentagon: PentagonIcon,
    Percent: PercentIcon,
    PersonStanding: PersonStandingIcon,
    PhilippinePeso: PhilippinePesoIcon,
    Phone: PhoneIcon,
    PhoneCall: PhoneCallIcon,
    PhoneForwarded: PhoneForwardedIcon,
    PhoneIncoming: PhoneIncomingIcon,
    PhoneMissed: PhoneMissedIcon,
    PhoneOff: PhoneOffIcon,
    PhoneOutgoing: PhoneOutgoingIcon,
    Pi: PiIcon,
    Piano: PianoIcon,
    Pickaxe: PickaxeIcon,
    PictureInPicture: PictureInPictureIcon,
    PictureInPicture2: PictureInPicture2Icon,
    PiggyBank: PiggyBankIcon,
    Pilcrow: PilcrowIcon,
    PilcrowLeft: PilcrowLeftIcon,
    PilcrowRight: PilcrowRightIcon,
    Pill: PillIcon,
    PillBottle: PillBottleIcon,
    Pin: PinIcon,
    PinOff: PinOffIcon,
    Pipette: PipetteIcon,
    Pizza: PizzaIcon,
    Plane: PlaneIcon,
    PlaneLanding: PlaneLandingIcon,
    PlaneTakeoff: PlaneTakeoffIcon,
    Play: PlayIcon,
    Plug: PlugIcon,
    Plug2: Plug2Icon,
    PlugZap: PlugZapIcon,
    Plus: PlusIcon,
    Pocket: PocketIcon,
    PocketKnife: PocketKnifeIcon,
    Podcast: PodcastIcon,
    Pointer: PointerIcon,
    PointerOff: PointerOffIcon,
    Popcorn: PopcornIcon,
    Popsicle: PopsicleIcon,
    PoundSterling: PoundSterlingIcon,
    Power: PowerIcon,
    PowerOff: PowerOffIcon,
    Presentation: PresentationIcon,
    Printer: PrinterIcon,
    PrinterCheck: PrinterCheckIcon,
    Projector: ProjectorIcon,
    Proportions: ProportionsIcon,
    Puzzle: PuzzleIcon,
    Pyramid: PyramidIcon,
    QrCode: QrCodeIcon,
    Quote: QuoteIcon,
    Rabbit: RabbitIcon,
    Radar: RadarIcon,
    Radiation: RadiationIcon,
    Radical: RadicalIcon,
    Radio: RadioIcon,
    RadioReceiver: RadioReceiverIcon,
    RadioTower: RadioTowerIcon,
    Radius: RadiusIcon,
    RailSymbol: RailSymbolIcon,
    Rainbow: RainbowIcon,
    Rat: RatIcon,
    Ratio: RatioIcon,
    Receipt: ReceiptIcon,
    ReceiptCent: ReceiptCentIcon,
    ReceiptEuro: ReceiptEuroIcon,
    ReceiptIndianRupee: ReceiptIndianRupeeIcon,
    ReceiptJapaneseYen: ReceiptJapaneseYenIcon,
    ReceiptPoundSterling: ReceiptPoundSterlingIcon,
    ReceiptRussianRuble: ReceiptRussianRubleIcon,
    ReceiptSwissFranc: ReceiptSwissFrancIcon,
    ReceiptText: ReceiptTextIcon,
    ReceiptTurkishLira: ReceiptTurkishLiraIcon,
    RectangleCircle: RectangleCircleIcon,
    RectangleEllipsis: RectangleEllipsisIcon,
    RectangleGoggles: RectangleGogglesIcon,
    RectangleHorizontal: RectangleHorizontalIcon,
    RectangleVertical: RectangleVerticalIcon,
    Recycle: RecycleIcon,
    Redo: RedoIcon,
    Redo2: Redo2Icon,
    RedoDot: RedoDotIcon,
    RefreshCcw: RefreshCcwIcon,
    RefreshCcwDot: RefreshCcwDotIcon,
    RefreshCw: RefreshCwIcon,
    RefreshCwOff: RefreshCwOffIcon,
    Refrigerator: RefrigeratorIcon,
    Regex: RegexIcon,
    RemoveFormatting: RemoveFormattingIcon,
    Repeat: RepeatIcon,
    Repeat1: Repeat1Icon,
    Repeat2: Repeat2Icon,
    Replace: ReplaceIcon,
    ReplaceAll: ReplaceAllIcon,
    Reply: ReplyIcon,
    ReplyAll: ReplyAllIcon,
    Rewind: RewindIcon,
    Ribbon: RibbonIcon,
    Rocket: RocketIcon,
    RockingChair: RockingChairIcon,
    RollerCoaster: RollerCoasterIcon,
    Rose: RoseIcon,
    Rotate3d: Rotate3dIcon,
    RotateCcw: RotateCcwIcon,
    RotateCcwKey: RotateCcwKeyIcon,
    RotateCcwSquare: RotateCcwSquareIcon,
    RotateCw: RotateCwIcon,
    RotateCwSquare: RotateCwSquareIcon,
    Route: RouteIcon,
    RouteOff: RouteOffIcon,
    Router: RouterIcon,
    Rows2: Rows2Icon,
    Rows3: Rows3Icon,
    Rows4: Rows4Icon,
    Rss: RssIcon,
    Ruler: RulerIcon,
    RulerDimensionLine: RulerDimensionLineIcon,
    RussianRuble: RussianRubleIcon,
    Sailboat: SailboatIcon,
    Salad: SaladIcon,
    Sandwich: SandwichIcon,
    Satellite: SatelliteIcon,
    SatelliteDish: SatelliteDishIcon,
    SaudiRiyal: SaudiRiyalIcon,
    Save: SaveIcon,
    SaveAll: SaveAllIcon,
    SaveOff: SaveOffIcon,
    Scale: ScaleIcon,
    Scale3d: Scale3dIcon,
    Scaling: ScalingIcon,
    Scan: ScanIcon,
    ScanBarcode: ScanBarcodeIcon,
    ScanEye: ScanEyeIcon,
    ScanFace: ScanFaceIcon,
    ScanHeart: ScanHeartIcon,
    ScanLine: ScanLineIcon,
    ScanQrCode: ScanQrCodeIcon,
    ScanSearch: ScanSearchIcon,
    ScanText: ScanTextIcon,
    School: SchoolIcon,
    Scissors: ScissorsIcon,
    ScissorsLineDashed: ScissorsLineDashedIcon,
    ScreenShare: ScreenShareIcon,
    ScreenShareOff: ScreenShareOffIcon,
    Scroll: ScrollIcon,
    ScrollText: ScrollTextIcon,
    Search: SearchIcon,
    SearchCheck: SearchCheckIcon,
    SearchCode: SearchCodeIcon,
    SearchSlash: SearchSlashIcon,
    SearchX: SearchXIcon,
    Section: SectionIcon,
    Send: SendIcon,
    SendHorizontal: SendHorizontalIcon,
    SendToBack: SendToBackIcon,
    SeparatorHorizontal: SeparatorHorizontalIcon,
    SeparatorVertical: SeparatorVerticalIcon,
    Server: ServerIcon,
    ServerCog: ServerCogIcon,
    ServerCrash: ServerCrashIcon,
    ServerOff: ServerOffIcon,
    Settings: SettingsIcon,
    Settings2: Settings2Icon,
    Shapes: ShapesIcon,
    Share: ShareIcon,
    Share2: Share2Icon,
    Sheet: SheetIcon,
    Shell: ShellIcon,
    Shield: ShieldIcon,
    ShieldAlert: ShieldAlertIcon,
    ShieldBan: ShieldBanIcon,
    ShieldCheck: ShieldCheckIcon,
    ShieldEllipsis: ShieldEllipsisIcon,
    ShieldHalf: ShieldHalfIcon,
    ShieldMinus: ShieldMinusIcon,
    ShieldOff: ShieldOffIcon,
    ShieldPlus: ShieldPlusIcon,
    ShieldQuestionMark: ShieldQuestionMarkIcon,
    ShieldUser: ShieldUserIcon,
    ShieldX: ShieldXIcon,
    Ship: ShipIcon,
    ShipWheel: ShipWheelIcon,
    Shirt: ShirtIcon,
    ShoppingBag: ShoppingBagIcon,
    ShoppingBasket: ShoppingBasketIcon,
    ShoppingCart: ShoppingCartIcon,
    Shovel: ShovelIcon,
    ShowerHead: ShowerHeadIcon,
    Shredder: ShredderIcon,
    Shrimp: ShrimpIcon,
    Shrink: ShrinkIcon,
    Shrub: ShrubIcon,
    Shuffle: ShuffleIcon,
    Sigma: SigmaIcon,
    Signal: SignalIcon,
    SignalHigh: SignalHighIcon,
    SignalLow: SignalLowIcon,
    SignalMedium: SignalMediumIcon,
    SignalZero: SignalZeroIcon,
    Signature: SignatureIcon,
    Signpost: SignpostIcon,
    SignpostBig: SignpostBigIcon,
    Siren: SirenIcon,
    SkipBack: SkipBackIcon,
    SkipForward: SkipForwardIcon,
    Skull: SkullIcon,
    Slack: SlackIcon,
    Slash: SlashIcon,
    Slice: SliceIcon,
    SlidersHorizontal: SlidersHorizontalIcon,
    SlidersVertical: SlidersVerticalIcon,
    Smartphone: SmartphoneIcon,
    SmartphoneCharging: SmartphoneChargingIcon,
    SmartphoneNfc: SmartphoneNfcIcon,
    Smile: SmileIcon,
    SmilePlus: SmilePlusIcon,
    Snail: SnailIcon,
    Snowflake: SnowflakeIcon,
    SoapDispenserDroplet: SoapDispenserDropletIcon,
    Sofa: SofaIcon,
    SolarPanel: SolarPanelIcon,
    Soup: SoupIcon,
    Space: SpaceIcon,
    Spade: SpadeIcon,
    Sparkle: SparkleIcon,
    Sparkles: SparklesIcon,
    Speaker: SpeakerIcon,
    Speech: SpeechIcon,
    SpellCheck: SpellCheckIcon,
    SpellCheck2: SpellCheck2Icon,
    Spline: SplineIcon,
    SplinePointer: SplinePointerIcon,
    Split: SplitIcon,
    Spool: SpoolIcon,
    Spotlight: SpotlightIcon,
    SprayCan: SprayCanIcon,
    Sprout: SproutIcon,
    Square: SquareIcon,
    SquareActivity: SquareActivityIcon,
    SquareArrowDown: SquareArrowDownIcon,
    SquareArrowDownLeft: SquareArrowDownLeftIcon,
    SquareArrowDownRight: SquareArrowDownRightIcon,
    SquareArrowLeft: SquareArrowLeftIcon,
    SquareArrowOutDownLeft: SquareArrowOutDownLeftIcon,
    SquareArrowOutDownRight: SquareArrowOutDownRightIcon,
    SquareArrowOutUpLeft: SquareArrowOutUpLeftIcon,
    SquareArrowOutUpRight: SquareArrowOutUpRightIcon,
    SquareArrowRight: SquareArrowRightIcon,
    SquareArrowUp: SquareArrowUpIcon,
    SquareArrowUpLeft: SquareArrowUpLeftIcon,
    SquareArrowUpRight: SquareArrowUpRightIcon,
    SquareAsterisk: SquareAsteriskIcon,
    SquareBottomDashedScissors: SquareBottomDashedScissorsIcon,
    SquareChartGantt: SquareChartGanttIcon,
    SquareCheck: SquareCheckIcon,
    SquareCheckBig: SquareCheckBigIcon,
    SquareChevronDown: SquareChevronDownIcon,
    SquareChevronLeft: SquareChevronLeftIcon,
    SquareChevronRight: SquareChevronRightIcon,
    SquareChevronUp: SquareChevronUpIcon,
    SquareCode: SquareCodeIcon,
    SquareDashed: SquareDashedIcon,
    SquareDashedBottom: SquareDashedBottomIcon,
    SquareDashedBottomCode: SquareDashedBottomCodeIcon,
    SquareDashedKanban: SquareDashedKanbanIcon,
    SquareDashedMousePointer: SquareDashedMousePointerIcon,
    SquareDashedTopSolid: SquareDashedTopSolidIcon,
    SquareDivide: SquareDivideIcon,
    SquareDot: SquareDotIcon,
    SquareEqual: SquareEqualIcon,
    SquareFunction: SquareFunctionIcon,
    SquareKanban: SquareKanbanIcon,
    SquareLibrary: SquareLibraryIcon,
    SquareM: SquareMIcon,
    SquareMenu: SquareMenuIcon,
    SquareMinus: SquareMinusIcon,
    SquareMousePointer: SquareMousePointerIcon,
    SquareParking: SquareParkingIcon,
    SquareParkingOff: SquareParkingOffIcon,
    SquarePause: SquarePauseIcon,
    SquarePen: SquarePenIcon,
    SquarePercent: SquarePercentIcon,
    SquarePi: SquarePiIcon,
    SquarePilcrow: SquarePilcrowIcon,
    SquarePlay: SquarePlayIcon,
    SquarePlus: SquarePlusIcon,
    SquarePower: SquarePowerIcon,
    SquareRadical: SquareRadicalIcon,
    SquareRoundCorner: SquareRoundCornerIcon,
    SquareScissors: SquareScissorsIcon,
    SquareSigma: SquareSigmaIcon,
    SquareSlash: SquareSlashIcon,
    SquareSplitHorizontal: SquareSplitHorizontalIcon,
    SquareSplitVertical: SquareSplitVerticalIcon,
    SquareSquare: SquareSquareIcon,
    SquareStack: SquareStackIcon,
    SquareStar: SquareStarIcon,
    SquareStop: SquareStopIcon,
    SquareTerminal: SquareTerminalIcon,
    SquareUser: SquareUserIcon,
    SquareUserRound: SquareUserRoundIcon,
    SquareX: SquareXIcon,
    SquaresExclude: SquaresExcludeIcon,
    SquaresIntersect: SquaresIntersectIcon,
    SquaresSubtract: SquaresSubtractIcon,
    SquaresUnite: SquaresUniteIcon,
    Squircle: SquircleIcon,
    SquircleDashed: SquircleDashedIcon,
    Squirrel: SquirrelIcon,
    Stamp: StampIcon,
    Star: StarIcon,
    StarHalf: StarHalfIcon,
    StarOff: StarOffIcon,
    StepBack: StepBackIcon,
    StepForward: StepForwardIcon,
    Stethoscope: StethoscopeIcon,
    Sticker: StickerIcon,
    StickyNote: StickyNoteIcon,
    Store: StoreIcon,
    StretchHorizontal: StretchHorizontalIcon,
    StretchVertical: StretchVerticalIcon,
    Strikethrough: StrikethroughIcon,
    Subscript: SubscriptIcon,
    Sun: SunIcon,
    SunDim: SunDimIcon,
    SunMedium: SunMediumIcon,
    SunMoon: SunMoonIcon,
    SunSnow: SunSnowIcon,
    Sunrise: SunriseIcon,
    Sunset: SunsetIcon,
    Superscript: SuperscriptIcon,
    SwatchBook: SwatchBookIcon,
    SwissFranc: SwissFrancIcon,
    SwitchCamera: SwitchCameraIcon,
    Sword: SwordIcon,
    Swords: SwordsIcon,
    Syringe: SyringeIcon,
    Table: TableIcon,
    Table2: Table2Icon,
    TableCellsMerge: TableCellsMergeIcon,
    TableCellsSplit: TableCellsSplitIcon,
    TableColumnsSplit: TableColumnsSplitIcon,
    TableOfContents: TableOfContentsIcon,
    TableProperties: TablePropertiesIcon,
    TableRowsSplit: TableRowsSplitIcon,
    Tablet: TabletIcon,
    TabletSmartphone: TabletSmartphoneIcon,
    Tablets: TabletsIcon,
    Tag: TagIcon,
    Tags: TagsIcon,
    Tally1: Tally1Icon,
    Tally2: Tally2Icon,
    Tally3: Tally3Icon,
    Tally4: Tally4Icon,
    Tally5: Tally5Icon,
    Tangent: TangentIcon,
    Target: TargetIcon,
    Telescope: TelescopeIcon,
    Tent: TentIcon,
    TentTree: TentTreeIcon,
    Terminal: TerminalIcon,
    TestTube: TestTubeIcon,
    TestTubeDiagonal: TestTubeDiagonalIcon,
    TestTubes: TestTubesIcon,
    TextAlignCenter: TextAlignCenterIcon,
    TextAlignEnd: TextAlignEndIcon,
    TextAlignJustify: TextAlignJustifyIcon,
    TextAlignStart: TextAlignStartIcon,
    TextCursor: TextCursorIcon,
    TextCursorInput: TextCursorInputIcon,
    TextInitial: TextInitialIcon,
    TextQuote: TextQuoteIcon,
    TextSearch: TextSearchIcon,
    TextSelect: TextSelectIcon,
    TextWrap: TextWrapIcon,
    Theater: TheaterIcon,
    Thermometer: ThermometerIcon,
    ThermometerSnowflake: ThermometerSnowflakeIcon,
    ThermometerSun: ThermometerSunIcon,
    ThumbsDown: ThumbsDownIcon,
    ThumbsUp: ThumbsUpIcon,
    Ticket: TicketIcon,
    TicketCheck: TicketCheckIcon,
    TicketMinus: TicketMinusIcon,
    TicketPercent: TicketPercentIcon,
    TicketPlus: TicketPlusIcon,
    TicketSlash: TicketSlashIcon,
    TicketX: TicketXIcon,
    Tickets: TicketsIcon,
    TicketsPlane: TicketsPlaneIcon,
    Timer: TimerIcon,
    TimerOff: TimerOffIcon,
    TimerReset: TimerResetIcon,
    ToggleLeft: ToggleLeftIcon,
    ToggleRight: ToggleRightIcon,
    Toilet: ToiletIcon,
    ToolCase: ToolCaseIcon,
    Tornado: TornadoIcon,
    Torus: TorusIcon,
    Touchpad: TouchpadIcon,
    TouchpadOff: TouchpadOffIcon,
    TowerControl: TowerControlIcon,
    ToyBrick: ToyBrickIcon,
    Tractor: TractorIcon,
    TrafficCone: TrafficConeIcon,
    TrainFront: TrainFrontIcon,
    TrainFrontTunnel: TrainFrontTunnelIcon,
    TrainTrack: TrainTrackIcon,
    TramFront: TramFrontIcon,
    Transgender: TransgenderIcon,
    Trash: TrashIcon,
    Trash2: Trash2Icon,
    TreeDeciduous: TreeDeciduousIcon,
    TreePalm: TreePalmIcon,
    TreePine: TreePineIcon,
    Trees: TreesIcon,
    Trello: TrelloIcon,
    TrendingDown: TrendingDownIcon,
    TrendingUp: TrendingUpIcon,
    TrendingUpDown: TrendingUpDownIcon,
    Triangle: TriangleIcon,
    TriangleAlert: TriangleAlertIcon,
    TriangleDashed: TriangleDashedIcon,
    TriangleRight: TriangleRightIcon,
    Trophy: TrophyIcon,
    Truck: TruckIcon,
    TruckElectric: TruckElectricIcon,
    TurkishLira: TurkishLiraIcon,
    Turntable: TurntableIcon,
    Turtle: TurtleIcon,
    Tv: TvIcon,
    TvMinimal: TvMinimalIcon,
    TvMinimalPlay: TvMinimalPlayIcon,
    Twitch: TwitchIcon,
    Twitter: TwitterIcon,
    Type: TypeIcon,
    TypeOutline: TypeOutlineIcon,
    Umbrella: UmbrellaIcon,
    UmbrellaOff: UmbrellaOffIcon,
    Underline: UnderlineIcon,
    Undo: UndoIcon,
    Undo2: Undo2Icon,
    UndoDot: UndoDotIcon,
    UnfoldHorizontal: UnfoldHorizontalIcon,
    UnfoldVertical: UnfoldVerticalIcon,
    Ungroup: UngroupIcon,
    University: UniversityIcon,
    Unlink: UnlinkIcon,
    Unlink2: Unlink2Icon,
    Unplug: UnplugIcon,
    Upload: UploadIcon,
    Usb: UsbIcon,
    User: UserIcon,
    UserCheck: UserCheckIcon,
    UserCog: UserCogIcon,
    UserLock: UserLockIcon,
    UserMinus: UserMinusIcon,
    UserPen: UserPenIcon,
    UserPlus: UserPlusIcon,
    UserRound: UserRoundIcon,
    UserRoundCheck: UserRoundCheckIcon,
    UserRoundCog: UserRoundCogIcon,
    UserRoundMinus: UserRoundMinusIcon,
    UserRoundPen: UserRoundPenIcon,
    UserRoundPlus: UserRoundPlusIcon,
    UserRoundSearch: UserRoundSearchIcon,
    UserRoundX: UserRoundXIcon,
    UserSearch: UserSearchIcon,
    UserStar: UserStarIcon,
    UserX: UserXIcon,
    Users: UsersIcon,
    UsersRound: UsersRoundIcon,
    Utensils: UtensilsIcon,
    UtensilsCrossed: UtensilsCrossedIcon,
    UtilityPole: UtilityPoleIcon,
    Variable: VariableIcon,
    Vault: VaultIcon,
    VectorSquare: VectorSquareIcon,
    Vegan: VeganIcon,
    VenetianMask: VenetianMaskIcon,
    Venus: VenusIcon,
    VenusAndMars: VenusAndMarsIcon,
    Vibrate: VibrateIcon,
    VibrateOff: VibrateOffIcon,
    Video: VideoIcon,
    VideoOff: VideoOffIcon,
    Videotape: VideotapeIcon,
    View: ViewIcon,
    Voicemail: VoicemailIcon,
    Volleyball: VolleyballIcon,
    Volume: VolumeIcon,
    Volume1: Volume1Icon,
    Volume2: Volume2Icon,
    VolumeOff: VolumeOffIcon,
    VolumeX: VolumeXIcon,
    Vote: VoteIcon,
    Wallet: WalletIcon,
    WalletCards: WalletCardsIcon,
    WalletMinimal: WalletMinimalIcon,
    Wallpaper: WallpaperIcon,
    Wand: WandIcon,
    WandSparkles: WandSparklesIcon,
    Warehouse: WarehouseIcon,
    WashingMachine: WashingMachineIcon,
    Watch: WatchIcon,
    Waves: WavesIcon,
    WavesLadder: WavesLadderIcon,
    Waypoints: WaypointsIcon,
    Webcam: WebcamIcon,
    Webhook: WebhookIcon,
    WebhookOff: WebhookOffIcon,
    Weight: WeightIcon,
    Wheat: WheatIcon,
    WheatOff: WheatOffIcon,
    WholeWord: WholeWordIcon,
    Wifi: WifiIcon,
    WifiCog: WifiCogIcon,
    WifiHigh: WifiHighIcon,
    WifiLow: WifiLowIcon,
    WifiOff: WifiOffIcon,
    WifiPen: WifiPenIcon,
    WifiSync: WifiSyncIcon,
    WifiZero: WifiZeroIcon,
    Wind: WindIcon,
    WindArrowDown: WindArrowDownIcon,
    Wine: WineIcon,
    WineOff: WineOffIcon,
    Workflow: WorkflowIcon,
    Worm: WormIcon,
    Wrench: WrenchIcon,
    X: XIcon,
    Youtube: YoutubeIcon,
    Zap: ZapIcon,
    ZapOff: ZapOffIcon,
    ZoomIn: ZoomInIcon,
    ZoomOut: ZoomOutIcon,
};
