import {
    InfinityIcon,
    AccessibilityIcon,
    ActivityIcon,
    AlarmClockIcon,
    AmbulanceIcon,
    AmphoraIcon,
    AnchorIcon,
    AngryIcon,
    AnnoyedIcon,
    AnvilIcon,
    ApertureIcon,
    AppleIcon,
    ArmchairIcon,
    AtomIcon,
    AudioLinesIcon,
    AudioWaveformIcon,
    AwardIcon,
    AxeIcon,
    BabyIcon,
    BananaIcon,
    BeanIcon,
    BeerIcon,
    BellIcon,
    BicepsFlexedIcon,
    BikeIcon,
    BinocularsIcon,
    BiohazardIcon,
    BirdIcon,
    BookIcon,
    BookOpenIcon,
    BotIcon,
    BottleWineIcon,
    BowArrowIcon,
    BoxIcon,
    BrainIcon,
    BugIcon,
    BuildingIcon,
    BusIcon,
    CakeIcon,
    CalculatorIcon,
    CandyIcon,
    CarIcon,
    CarrotIcon,
    CatIcon,
    CherryIcon,
    ChessBishopIcon,
    ChessKingIcon,
    ChessKnightIcon,
    ChessPawnIcon,
    ChessQueenIcon,
    ChessRookIcon,
    ChurchIcon,
    CitrusIcon,
    ClapperboardIcon,
    CloudDrizzleIcon,
    CoffeeIcon,
    CogIcon,
    CookieIcon,
    CookingPotIcon,
    CroissantIcon,
    CrosshairIcon,
    CrownIcon,
    CupSodaIcon,
    DicesIcon,
    DogIcon,
    DonutIcon,
    DramaIcon,
    DrillIcon,
    DropletIcon,
    DrumIcon,
    DrumstickIcon,
    DumbbellIcon,
    EvChargerIcon,
    FilmIcon,
    FishIcon,
    FlameIcon,
    FlaskConicalIcon,
    Flower2Icon,
    FootprintsIcon,
    FrownIcon,
    FuelIcon,
    GaugeIcon,
    GavelIcon,
    GemIcon,
    GhostIcon,
    GlobeIcon,
    GraduationCapIcon,
    GrapeIcon,
    GuitarIcon,
    HamIcon,
    HamburgerIcon,
    HammerIcon,
    HandbagIcon,
    HatGlassesIcon,
    HeadphonesIcon,
    HeartCrackIcon,
    HeartIcon,
    HelicopterIcon,
    HourglassIcon,
    HouseIcon,
    IceCreamConeIcon,
    JoystickIcon,
    KeyRoundIcon,
    LaughIcon,
    LightbulbIcon,
    LocateIcon,
    MagnetIcon,
    MailIcon,
    MartiniIcon,
    MegaphoneIcon,
    MehIcon,
    MicIcon,
    MicVocalIcon,
    MicroscopeIcon,
    MoonIcon,
    MotorbikeIcon,
    MusicIcon,
    NfcIcon,
    NutIcon,
    OmegaIcon,
    OrigamiIcon,
    PaletteIcon,
    PandaIcon,
    PaperclipIcon,
    PartyPopperIcon,
    PawPrintIcon,
    PersonStandingIcon,
    PhoneIcon,
    PianoIcon,
    PickaxeIcon,
    PiggyBankIcon,
    PizzaIcon,
    PlaneIcon,
    PlusIcon,
    PopcornIcon,
    PopsicleIcon,
    PuzzleIcon,
    PyramidIcon,
    RabbitIcon,
    RadiationIcon,
    RainbowIcon,
    RatIcon,
    RibbonIcon,
    RocketIcon,
    RoseIcon,
    SailboatIcon,
    ScaleIcon,
    SchoolIcon,
    ScrollIcon,
    ShellIcon,
    ShipWheelIcon,
    ShirtIcon,
    ShovelIcon,
    ShowerHeadIcon,
    ShrimpIcon,
    SkullIcon,
    SmileIcon,
    SnailIcon,
    SnowflakeIcon,
    SoupIcon,
    SpeakerIcon,
    SprayCanIcon,
    SproutIcon,
    SquirrelIcon,
    StampIcon,
    StarIcon,
    StethoscopeIcon,
    SunIcon,
    SwordIcon,
    TelescopeIcon,
    TentIcon,
    ThumbsDownIcon,
    ThumbsUpIcon,
    ToiletIcon,
    TornadoIcon,
    TreePalmIcon,
    TreePineIcon,
    TrophyIcon,
    TruckIcon,
    TurtleIcon,
    TvIcon,
    UmbrellaIcon,
    WebhookIcon,
    WindIcon,
    WormIcon,
    WrenchIcon,
    ZapIcon,
} from "lucide-vue-next";

export const Icons = {
    Accessibility: AccessibilityIcon,
    Activity: ActivityIcon,
    "Alarm Clock": AlarmClockIcon,
    Ambulance: AmbulanceIcon,
    Amphora: AmphoraIcon,
    Anchor: AnchorIcon,
    "Animal Bird": BirdIcon,
    "Animal Bug": BugIcon,
    "Animal Cat": CatIcon,
    "Animal Dog": DogIcon,
    "Animal Fish": FishIcon,
    "Animal Panda": PandaIcon,
    "Animal Rabbit": RabbitIcon,
    "Animal Rat": RatIcon,
    "Animal Shrimp": ShrimpIcon,
    "Animal Snail": SnailIcon,
    "Animal Squirrel": SquirrelIcon,
    "Animal Turtle": TurtleIcon,
    "Animal Worm": WormIcon,
    Anvil: AnvilIcon,
    Aperture: ApertureIcon,
    Apple: AppleIcon,
    Armchair: ArmchairIcon,
    Atom: AtomIcon,
    "Audio Lines": AudioLinesIcon,
    "Audio Waveform": AudioWaveformIcon,
    Award: AwardIcon,
    Axe: AxeIcon,
    Baby: BabyIcon,
    Banana: BananaIcon,
    Bean: BeanIcon,
    Beer: BeerIcon,
    Bell: BellIcon,
    "Biceps Flexed": BicepsFlexedIcon,
    Bike: BikeIcon,
    Binoculars: BinocularsIcon,
    Biohazard: BiohazardIcon,
    Book: BookIcon,
    "Book Open": BookOpenIcon,
    Bot: BotIcon,
    "Bottle Wine": BottleWineIcon,
    "Bow Arrow": BowArrowIcon,
    Box: BoxIcon,
    Brain: BrainIcon,
    Building: BuildingIcon,
    Bus: BusIcon,
    Cake: CakeIcon,
    Calculator: CalculatorIcon,
    Candy: CandyIcon,
    Car: CarIcon,
    Carrot: CarrotIcon,
    Cherry: CherryIcon,
    "Chess Bishop": ChessBishopIcon,
    "Chess King": ChessKingIcon,
    "Chess Knight": ChessKnightIcon,
    "Chess Pawn": ChessPawnIcon,
    "Chess Queen": ChessQueenIcon,
    "Chess Rook": ChessRookIcon,
    Church: ChurchIcon,
    Citrus: CitrusIcon,
    "Clapper board": ClapperboardIcon,
    "Cloud Drizzle": CloudDrizzleIcon,
    Coffee: CoffeeIcon,
    Cog: CogIcon,
    Cookie: CookieIcon,
    "Cooking Pot": CookingPotIcon,
    Croissant: CroissantIcon,
    Crosshair: CrosshairIcon,
    Crown: CrownIcon,
    "Cup Soda": CupSodaIcon,
    Dice: DicesIcon,
    Donut: DonutIcon,
    Drama: DramaIcon,
    Drill: DrillIcon,
    Droplet: DropletIcon,
    Drum: DrumIcon,
    Drumstick: DrumstickIcon,
    Dumbbell: DumbbellIcon,
    "Ev Charger": EvChargerIcon,
    "Face Angry": AngryIcon,
    "Face Annoyed": AnnoyedIcon,
    "Face Frown": FrownIcon,
    "Face Laugh": LaughIcon,
    "Face Meh": MehIcon,
    "Face Smile": SmileIcon,
    Film: FilmIcon,
    Flame: FlameIcon,
    Flask: FlaskConicalIcon,
    Flower: Flower2Icon,
    Footprints: FootprintsIcon,
    Fuel: FuelIcon,
    Gauge: GaugeIcon,
    Gavel: GavelIcon,
    Gem: GemIcon,
    Ghost: GhostIcon,
    Globe: GlobeIcon,
    "Graduation Cap": GraduationCapIcon,
    Grape: GrapeIcon,
    Guitar: GuitarIcon,
    Ham: HamIcon,
    Hamburger: HamburgerIcon,
    Hammer: HammerIcon,
    Handbag: HandbagIcon,
    "Hat Glasses": HatGlassesIcon,
    Headphones: HeadphonesIcon,
    "Heart Broken": HeartCrackIcon,
    Heart: HeartIcon,
    Helicopter: HelicopterIcon,
    Hourglass: HourglassIcon,
    House: HouseIcon,
    "Ice Cream Cone": IceCreamConeIcon,
    Infinity: InfinityIcon,
    Joystick: JoystickIcon,
    "Key Round": KeyRoundIcon,
    Lightbulb: LightbulbIcon,
    Locate: LocateIcon,
    Magnet: MagnetIcon,
    Mail: MailIcon,
    Martini: MartiniIcon,
    Megaphone: MegaphoneIcon,
    "Mic Vocal": MicVocalIcon,
    Mic: MicIcon,
    Microscope: MicroscopeIcon,
    Moon: MoonIcon,
    Motorbike: MotorbikeIcon,
    Music: MusicIcon,
    Nfc: NfcIcon,
    Nut: NutIcon,
    Omega: OmegaIcon,
    Origami: OrigamiIcon,
    Palette: PaletteIcon,
    Paperclip: PaperclipIcon,
    "Party Popper": PartyPopperIcon,
    "Paw Print": PawPrintIcon,
    "Person Standing": PersonStandingIcon,
    Phone: PhoneIcon,
    Piano: PianoIcon,
    Pickaxe: PickaxeIcon,
    "Piggy Bank": PiggyBankIcon,
    Pizza: PizzaIcon,
    Plane: PlaneIcon,
    Plus: PlusIcon,
    Popcorn: PopcornIcon,
    Popsicle: PopsicleIcon,
    Puzzle: PuzzleIcon,
    Pyramid: PyramidIcon,
    Radiation: RadiationIcon,
    Rainbow: RainbowIcon,
    Ribbon: RibbonIcon,
    Rocket: RocketIcon,
    Rose: RoseIcon,
    Sailboat: SailboatIcon,
    Scale: ScaleIcon,
    School: SchoolIcon,
    Scroll: ScrollIcon,
    Shell: ShellIcon,
    "Ship Wheel": ShipWheelIcon,
    Shirt: ShirtIcon,
    Shovel: ShovelIcon,
    "Shower Head": ShowerHeadIcon,
    Skull: SkullIcon,
    Snowflake: SnowflakeIcon,
    Soup: SoupIcon,
    Speaker: SpeakerIcon,
    "Spray Can": SprayCanIcon,
    Sprout: SproutIcon,
    Stamp: StampIcon,
    Star: StarIcon,
    Stethoscope: StethoscopeIcon,
    Sun: SunIcon,
    Sword: SwordIcon,
    Telescope: TelescopeIcon,
    Tent: TentIcon,
    "Thumbs Down": ThumbsDownIcon,
    "Thumbs Up": ThumbsUpIcon,
    Toilet: ToiletIcon,
    Tornado: TornadoIcon,
    "Tree Palm": TreePalmIcon,
    "Tree Pine": TreePineIcon,
    Trophy: TrophyIcon,
    Truck: TruckIcon,
    Tv: TvIcon,
    Umbrella: UmbrellaIcon,
    Webhook: WebhookIcon,
    Wind: WindIcon,
    Wrench: WrenchIcon,
    Zap: ZapIcon,
};
